### ISSUE TITLE
Crash changing blend mode

### ISSUE THREAD

**Issue by ebarranco** [MaurycyLiebner/enve#10]
Changing the blend mode makes Enve crash [I show you here.](https://youtu.be/ncJcf0luYeg)

**Comment by MaurycyLiebner** [comment]
I cannot reproduce the issue. It is probably connected to #6, as some blend modes (DstIn, SrcIn, DstATop) are currently using fill paths (to clear the area outside of the the object texture's range), and they may be rendered using your GPU. I will try to find a way to do this without paths.

**Comment by ebarranco** [comment]
You're right if I move the setting's slider to Strong GPU preference the crash never happen.

**Comment by MaurycyLiebner** [comment]
If everything goes well a new build should be available in 30 minutes.

**Comment by ebarranco** [comment]
Great! I'll be pending.

**Comment by ebarranco** [comment]
The issue seems resolved with the default settings. Thanks.
