### ISSUE TITLE
I am not able to select a object...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#101]
I am not able to select a object... somehow, I was just testing, and I drew a messy circle with the "Draw path mode" tool and now I am not able to select it with cursor nor move it or do anything with it... It is "Path 18" object

see attached *.ev file...

[pan_zemiank_shadows_eyes test.ev.zip](https://github.com/MaurycyLiebner/enve/files/4495164/pan_zemiank_shadows_eyes.test.ev.zip)

**Comment by MaurycyLiebner** [comment]
The path is corrupted. It has NaN (not a number) control point values. I do not know how this happened, probably there is a bug somewhere in the code. Just delete it. I will be on the lookout for the bug.
