### ISSUE TITLE
Adding a keyframe to a paths crashes Enve

### ISSUE THREAD

**Issue by larscwallin** [MaurycyLiebner/enve#105]
Version:
Enve 4_25_20 (splash screen says 0.0.0)

Platform:
Windows

To replicate:
1. Create new project
2. Create a new path
3. In the timeline expand the path, select the "paths" item 
4. Right click the item and choose "Add Key"
5. 🧨💥

**Comment by MaurycyLiebner** [comment]
Thank you for reporting. That's a newly introduced bug, should be fixed with the next release.

**Comment by MaurycyLiebner** [comment]
The newest (4/26/20) Windows release fixes this issue.
