### ISSUE TITLE
Can not load *.xev.

### ISSUE THREAD

**Issue by hansnolte** [MaurycyLiebner/enve#108]
If I save as * .xev I can no longer load the file.
Enve saves the * .xev in binary format and not in XML.
![xev](https://user-images.githubusercontent.com/7922627/80375713-04324a80-8899-11ea-8245-62bfaf41bead.jpg)

Testscene:
[Motion_Blur-in-xev-format.zip](https://github.com/MaurycyLiebner/enve/files/4539758/Motion_Blur-in-xev-format.zip)

**Comment by MaurycyLiebner** [comment]
`Enve saves the * .xev in binary format and not in XML.`
Xev is a zip file with XML-based content. You can rename the file to *.zip, unpack, and then see its content.

**Comment by MaurycyLiebner** [comment]
You can grab a new (4/27/20) release.

**Comment by hansnolte** [comment]
Thank you Maurycy,

the loading of *.xev and Motion Blur work properly.

A small cosmetic change.
In all Save dialogs Open is displayed instead of Save.
![save](https://user-images.githubusercontent.com/7922627/80457606-dfd57d00-892f-11ea-9534-8dcb47653992.jpg)


And a small question about the restrictions on exporting SVG animations.
What is all supported.
In this example the Letter Spacing Animation and Motion Blur are not exported.

Xev and SVG:
[Motion-Blur.zip](https://github.com/MaurycyLiebner/enve/files/4543924/Motion-Blur.zip)

**Comment by MaurycyLiebner** [comment]
The way enve works is completely different from SVG. Some enve features can be translated into SVG, some cannot. I think that letter spacing could be exported, but motion blur cannot - it isn't supported by SVG.

**Comment by hansnolte** [comment]
Thanks for your answer Maurycy,

**Comment by MaurycyLiebner** [comment]
I will add letter/word spacing today. SVG does not support multi-line text, so no line spacing.

**Comment by hansnolte** [comment]
Great!!!
