### ISSUE TITLE
Crash when applying Motion Blur effect

### ISSUE THREAD

**Issue by samirosman** [MaurycyLiebner/enve#110]
Version: Enve Continuous release - enve-3e0971d-x86_64.Appimage
OS: Linux Mint 18.3 Cinnamon 64-bit
GPU: Nvidia GTX 780m
CPU: Intel 4th Gen Core i7

Steps to reproduce:
1. Create a circle on canvas
2. Animate the position
3. Add a motion blue effect from the right click menu>raster effects>motion blur
4. Play the animation
5. Crash

**Comment by samirosman** [comment]
Motion Blur works in the latest enve-e0d9d8e-x86_64.appimage

**Comment by MaurycyLiebner** [comment]
Yes, the issue was fixed few hours before your post.
Thank you for reporting. If you encounter other bugs, please report them.
