### ISSUE TITLE
libenvecore.so: undefined reference to SkStroke: ...

### ISSUE THREAD

**Issue by eszlari** [MaurycyLiebner/enve#112]
```
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /run/build/enve/_build/src/app/../core/libenvecore.so: undefined reference to `SkBase64::Encode(void const*, unsigned long, void*, char const*)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /run/build/enve/_build/src/app/../core/libenvecore.so: undefined reference to `SkStroke::strokePath(SkPath const&, SkPath*) const'
collect2: error: ld returned 1 exit status
```
I'm trying to build enve with a shared library version of skia (`is_component_build=true`), but I can't get it to work. Any idea?

**Comment by MaurycyLiebner** [comment]
SkStroke and SkBase64 are not part of public Skia api, but they are used by enve, this is not a problem when linking statically, dynamic linkining is a different story.
You have to add **SK_API** to class declaration, e.g., `class SK_API SkStroke {` in **src/core/SkStroke.h** same for **include/utils/SkBase64.h**

**Comment by MaurycyLiebner** [comment]
Just out of curiosity, why are you building with a shared library version of skia?

**Comment by eszlari** [comment]
I wanted to link against system libraries. Anyway, I'm using the static version.
