### ISSUE TITLE
((feature request)) window transparent 

### ISSUE THREAD

**Issue by jointoday** [MaurycyLiebner/enve#117]
**Window Transparent** | 
---------------------- | 
![transparentx.gif](https://i.postimg.cc/zvczft8t/transparentx.gif) |

**Comment by MaurycyLiebner** [comment]
I don't get it. You want me to add a possibility of making the main enve window transparent?
You can always make a screenshot and then add the image to enve.

**Comment by jointoday** [comment]
Yes, if main enve window is transparent it's opening up rotoscoping technique. For example, walking person into the sun video + flying car video + walking cat video + burning house video +  burning earth video then make it into 1 frame. It's easy if using rotoscoping technique but a lot difficult if make a screenshot and then add the image to enve.

**Comment by MaurycyLiebner** [comment]
You can add videos to enve, probably better and easier than transparent window.

**Comment by jointoday** [comment]
Nice! I thought enve add images only. Thanks for info.
