### ISSUE TITLE
WebM output

### ISSUE THREAD

**Issue by prokoudine** [MaurycyLiebner/enve#12]
It would be great to have WebM/VP9 output support in Enve.

**Comment by MaurycyLiebner** [comment]
Enve already supports WebM/VP9 output.
I should probably give checkboxes a white border, to make them more visible.
![i12](https://user-images.githubusercontent.com/16670651/71250943-3b0fb700-2321-11ea-91ad-a864fb1799b8.png)
.

**Comment by prokoudine** [comment]
Oh indeed, I totally missed that. Quick nitpick: when I select WebM, the codec combo gives me VP8 and VP9 options twice.

Suggestion: maybe add WebM to the default list?

**Comment by MaurycyLiebner** [comment]
Thank you for pointing that out.
"VP8/VP9 (VAAPI)" has the same codec id as "libvpx VP8/VP9", and that's why the codec is displayed twice, it should show 4 different codecs, should be easy to fix.

I can add WebM to the default list.
