### ISSUE TITLE
Rulers (Move along Axis)

### ISSUE THREAD

**Issue by magdesign** [MaurycyLiebner/enve#123]
Tried to move a rectangle over the canvas in x direction (by mouse),
wanted to keep the y position, only change the x postion.

Usually we can press CTRL or SHIFT and then moving directions for selected objects are some kind of locked.

Would be nice to have...

![ruler_move](https://user-images.githubusercontent.com/5273166/81300486-086c1e00-9078-11ea-9535-c35871148f98.gif)

**Comment by MaurycyLiebner** [comment]
Press x or y on the keyboard while moving.

**Comment by magdesign** [comment]
Yes, similar to Blender, thanks!

I guess there is some kind of weird display behavior bug:
Pressed x and moved the rectangle and it visually starts to jump in Y the more I move:
![move_x_jump](https://user-images.githubusercontent.com/5273166/81303103-8f6ec580-907b-11ea-8322-08f4ac32aa64.gif)

Ubuntu 18.04 LTS

**Comment by MaurycyLiebner** [comment]
> Yes, similar to Blender, thanks!

Yes! That's were I'm coming from.

> I guess there is some kind of weird display behavior bug:
>  Pressed x and moved the rectangle and it visually starts to jump in Y the more I move:

That's not right. ;)

**Comment by MaurycyLiebner** [comment]
Ok, I know where is the issue. When you hold the x key it switches back and forth between constrained and unconstrained move behavior. You should press and release the x key instead.

**Comment by magdesign** [comment]
My stupid.... In Blender I would do it the similar way... finally got it:

1.) select the rectangle
2.) hit G
3.) hit X
4.) move the object

lets train the brain to think blender not inkscape... ;)
