### ISSUE TITLE
Can not load Xev in enve 5_7_20

### ISSUE THREAD

**Issue by hansnolte** [MaurycyLiebner/enve#128]
Hi Maurycy,

the Xev-Bug is back in.
![xev-error](https://user-images.githubusercontent.com/7922627/81568651-5e093900-939e-11ea-8eaf-8d191a9d29ce.jpg)

One more little annoying thing.
Enve does not remember the folder.
If I want to save a scene with save as, I always end up in the C:\Users\MyName folder

**Comment by MaurycyLiebner** [comment]
If you are referencing a different issue please write the number in the description, e.g., #128, because I do not remember this issue.
How did you open the file? From the welcome dialog? From the menu bar?

**Comment by hansnolte** [comment]
> If you are referencing a different issue please write the number in the description, e.g., #128, because I do not remember this issue.

Okay.




> How did you open the file? From the welcome dialog? From the menu bar?

With Double click. 
When I saw the Requester error, I didn't even think to test the welcome dialog and the menu bar

**Comment by MaurycyLiebner** [comment]
I think everything is working now, reopen if am mistaken.
