### ISSUE TITLE
Can I steal your code?

### ISSUE THREAD

**Issue by sukhchainn** [MaurycyLiebner/enve#134]
Can I take parts of your code and use it in my personal project?
If I do that, then do I have to make my repository open source?

**Comment by MaurycyLiebner** [comment]
You can read about enve license [here](https://github.com/MaurycyLiebner/enve/blob/master/LICENSE.md).
I do not expect you to read the whole thing, but there are some short bullet points on the top (**Permissions**, **Limitations**, **Conditions**).

**Comment by MaurycyLiebner** [comment]
My understanding:
If you will be the only user of the code (including executables) then you can pretty much do whatever you want. If you want to publish your work in any way - you will have to make it opensource, under GPL license.

**Comment by sukhchainn** [comment]
Ok bro.
We good! I'm gonna use it for personal in-house production only, your code won't be seeing no one man.

**Comment by vladimir-firefly** [comment]
I'm also not a lawyer, but from my undestanding you'll have to keep your repository private, if it happens to get public, for whatever reason, it will have to be gpl3 too.
