### ISSUE TITLE
Flipbook objects?

### ISSUE THREAD

**Issue by Skrylar** [MaurycyLiebner/enve#136]
It might be a good idea to have a "flipbook" group where changing a property changes which child of the group is currently visible. I've seen such in some mixed animation modes where ex. part of motion is tweened vectors but then major changes switch layers.

It is possible to keyframe opacity but that's clunky (you have to key each image's opacity, drag the slider between extremes, ... lot of clicking for a common task.)

I saw that videos allow you to keyframe which frame they use. So one could draw ex. mouth states and render those to frames, then reimport the video and set the frame without interpolation. But that requires extra steps and I'm not sure artists enjoy that.

**Comment by dadoprom** [comment]
yes, this is called "Switch object" I believe... great for animating lips - mouth shapes, and also hand gestures... and so on...
