### ISSUE TITLE
Imported filenames and their timeline representation do not match

### ISSUE THREAD

**Issue by vladimir-firefly** [MaurycyLiebner/enve#137]
I think one screenshot could explain a lot.

![Screenshot from 2020-05-22 20-26-19](https://user-images.githubusercontent.com/63293121/82698382-f3dc7800-9c6a-11ea-9f9a-d3b273d6e19f.png)

Dragging files from Files dialog to timeline make all sorts of crazy "interventions" to the layer name. Extensions get glued to filename itself, numbers at the beginning are trimmed and non-ASCII characters are simply ignored.

**Comment by MaurycyLiebner** [comment]
Object names have to follow strict rules because they can be referenced by expressions.

**Comment by vladimir-firefly** [comment]
Thanx for clarifying. I should pay attention to how I name my stuff in the future.
