### ISSUE TITLE
Impossible to grab multiple objects by Visibility range rectangle and drag them together

### ISSUE THREAD

**Issue by vladimir-firefly** [MaurycyLiebner/enve#138]
If I grab one Visibility range indicator and move it in time, keyframes get dragged along, which is what I'd expect. But it isn't possible to grab multiple (multiobject) visibility ranges and position them together.

Assuming shift+click to select multiple even make sense in this context, from the design point of view.

**Comment by MaurycyLiebner** [comment]
Hold shift while moving a visibility range, and all selected object visibility ranges will move. Is this a solution to your issue?

**Comment by vladimir-firefly** [comment]
Thanks for implementing this feature so fast!
I like that the functionality is now there, but I guess it is a bit inconsistent with the rest of the GUI. Selecting multiple objects/nodes/whatever doesn't need shift held down in order for you to operate on that selection. I think this could work well without shift while dragging.

I'm just talking about UX inconsistency here, but it's nice to have the functionality in place anyway. You can decide if this is a new feature request, a bug, or even if I should open a new report at all. There are some more remarks on the subject I could add, GUI related, that is...
