### ISSUE TITLE
Among the donation options, which has your preference?

### ISSUE THREAD

**Issue by JobLeonard** [MaurycyLiebner/enve#142]
I see that you provide multiple ways to support the development of this project. For me they are equally convenient, but what about you? Do you have a preferred mode of support?

Thanks, keep up the good work!

**Comment by MaurycyLiebner** [comment]
Most donations I receive are made through Patreon. The only bad thing is that Patreon is USD only, which means double currency conversion occurs (from donor's currency to USD, and from USD to my currency) if the donor uses a different currency than USD, but that's not that big of a deal.
I am yet to receive anything through Liberapay, so I cannot comment on that.
PayPal donations are quite convenient, can be made using any currency.

I would say, use Patreon for recurring donations, and PayPal for one-time donations.

Thank you, trying my best.
