### ISSUE TITLE
Duplicate and flip reverses the direction of the mouse movement.

### ISSUE THREAD

**Issue by EdisonMuniz** [MaurycyLiebner/enve#145]
I duplicated and fliped the character's hand.
Now when I rotate (R) the hand goes in the opposite direction of the mouse movement.

![Duplicate and flip](https://user-images.githubusercontent.com/58235690/83329171-58e13080-a25e-11ea-9068-50219f61e67f.png)

**Comment by MaurycyLiebner** [comment]
Rotation occurs in object's local coordinates. If object's parent has a negative scale, it appears as if the rotation was in the opposite direction, when in fact the rotation occurs in the direction of the mouse movement in the local coordinates and then is flipped.
