### ISSUE TITLE
Picking color through color widget (color dock) does not work...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#149]
Picking color through color widget (color dock, Fill > Flat color) does not work... or is somehow broken. It always pics black color and after picking color with picker you are also not able to change the hex color value. And after using the color picker, the keyboard shortcuts of Enve stop working... I can not use G to move object, R to rotate or Ctrl + z for undo and so on... BUT, I noticed that after switching to another aplication on the taskbar and switching back to Enve, the shortcuts start to work again and also I am able to change the hex color value again...

To reproduce the issue:
1. Draw two circles with diferent colors
2. Try to pick color from one circle to the other

**Comment by MaurycyLiebner** [comment]
Works fine when using AppImage / exe. Which release are you using?

**Comment by MaurycyLiebner** [comment]
How about now?

**Comment by dadoprom** [comment]
now when picking the color, color does not change at all, but when I click on canvas and than select again the object the shortcuts start to work... This is very strange, there must be something in my eniroment causing this... I use kde plasma (Kde Neon 5.18.5, KDE frameworks 5.70.0, Qt version 5.14.2), so perhaps QT issue, hmm... I really have no clue. 

I have also Window Maker installed here on the same machine and when running Enve here, there is something really strange happening when click on the picker - see the video, maybe it is some kind of clue :)

I tested this latest appimage on my other computer with gnome (pop os 19.10) and there the issue is not happening, it is ok, working nice

**Comment by dadoprom** [comment]
here is the video of enve in wmaker: [wmaker-enve-color-picker.zip](https://github.com/MaurycyLiebner/enve/files/4711699/wmaker-enve-color-picker.zip)

**Comment by dadoprom** [comment]
Oh, I see... the picker - its coordinates are somehow moved and it is picking the color from the canvas instead of from the object... or?

**Comment by dadoprom** [comment]
ok, this is happening to me because I recently pluged in a second screen... when I turn off the second screen, the picer works fine.

**Comment by MaurycyLiebner** [comment]
Please test the double screen setup with the newest release.

**Comment by dadoprom** [comment]
Still not working here...
See how does it behave in the video: [bug-video.zip](https://github.com/MaurycyLiebner/enve/files/4712774/bug-video.zip)

**Comment by MaurycyLiebner** [comment]
How about now?

**Comment by dadoprom** [comment]
plasma, 2 screens - not picking color, see video: [pickcolor-plasma.zip](https://github.com/MaurycyLiebner/enve/files/4719355/pickcolor-plasma.zip)

wmaker, 2 screens - working, see video: [pickcolor-wmaker.zip](https://github.com/MaurycyLiebner/enve/files/4719356/pickcolor-wmaker.zip)

gnome, 1 screen - works

**Comment by MaurycyLiebner** [comment]
Does it work with plasma now?

**Comment by dadoprom** [comment]
plasma - still not picking color

**Comment by MaurycyLiebner** [comment]
> plasma - still not picking color

That's kinda ridiculous. Seems like there's some funky behaviour on KDE Plasma's part.
Please test the next release and show me the terminal output.

**Comment by dadoprom** [comment]
[pickcolor-plasma.zip](https://github.com/MaurycyLiebner/enve/files/4723426/pickcolor-plasma.zip)

**Comment by MaurycyLiebner** [comment]
How about now?

**Comment by dadoprom** [comment]
not working

[pickcolor-plasma.zip](https://github.com/MaurycyLiebner/enve/files/4724027/pickcolor-plasma.zip)

**Comment by dadoprom** [comment]
it works, thank you :)
