### ISSUE TITLE
Pressure sensitivity etc. support for graphic tablets

### ISSUE THREAD

**Issue by prokoudine** [MaurycyLiebner/enve#15]
Unsure if this is already in your internal roadmap, but having support for pressure sensitivity, tilt, rotation etc. for graphic tablets would be great.

You might want taking a look at what Krita devs do. They rely on Qt's native support but patch Qt when making binary builds. All the patches are here: https://invent.kde.org/kde/krita/tree/master/3rdparty/ext_qt.

**Comment by MaurycyLiebner** [comment]
Enve already uses Qt's native pressure/tilt support.
I will make sure it works later today.
Does it not work on your setup?

**Comment by prokoudine** [comment]
Nope, I get no pressure sensitivity with my old Wacom Graphire 3. Works in other applications like GIMP though.

**Comment by MaurycyLiebner** [comment]
You are correct, it does not work when I use the AppImage.
Funny thing is that it works with enve-0.0.0, and when I build it on my PC.
Probably something to do with Travis CI build (Qt related).

**Comment by prokoudine** [comment]
Agata from the Krita team told me they submitted their patches to upstream Qt, to quote:

> most of them submitted upstream. some applied in 5.12, some in 5.13, some in 5.14...

So yeah, it could have something to do with the version of Qt you use in Travis.

**Comment by MaurycyLiebner** [comment]
Sadly this did not fix the issue. It may be related to different configure options being used to build packages contained in the beineri ppa, or maybe something else. I will have to test it locally.

**Comment by MaurycyLiebner** [comment]
Finally made Travic CI builds work with the official Qt packages. Pressure sensitivity works.
