### ISSUE TITLE
Enve's ability to export to image sequence in svg.

### ISSUE THREAD

**Issue by Gilraiser** [MaurycyLiebner/enve#152]
Hi. I think it is very important for Enve to have the ability to export to svg image stream. Because it is a widely used format, it allows to preserve each frame by separate files, there is no loss of quality when editing in other vector graphics programs and offers versatility of use for artists. Thank you. I hope the suggestion is helpful.

**Comment by MaurycyLiebner** [comment]
Enve can export animated SVG. I don't see the point of SVG sequences. Exporting an animation as SVG sequence only to then edit it frame by frame makes no sense. What would be the use of an SVG sequence? Is there any software that supports SVG sequences?

**Comment by Gilraiser** [comment]
Hello Mauricy. Thanks for answering. In fact there is a program called tupitube desk. It is vector graphics and frame by frame animation and allows export to svg sequence. What this software has is that it does not have as many tools for vector drawing and animation as Enve has until now. The meaning for me of being able to export to a svg sequence in an animation program is that you can add effects and modifications that Enve does not yet have with other programs such as inkscape or illustrator without fear of considerable loss in the quality of images such as it would be exporting it to png or jpg sequence which degrades the quality a little when editing. Being able to export the animation in separate frames per file offers another alternative for preserving the work done that guarantees that it will not be degraded or damaged when opened with other software in the future. Thank you for creating this software. regards

https://www.maefloresta.com/

**Comment by MaurycyLiebner** [comment]
> In fact there is a program called tupitube desk. It is vector graphics and frame by frame animation and allows export to svg sequence. 

I was more interested in programs that can import the sequences, not export it. What's the point of having SVG sequences if you cannot use them anywhere?

> The meaning for me of being able to export to a svg sequence in an animation program is that you can add effects and modifications that Enve does not yet have with other programs such as inkscape or illustrator

Lets say you have a very short animation with 200 frames (~8 seconds) if you want to add anything to the SVG sequence you would have to edit each of 200 files separately. It's highly impractical.

**Comment by Gilraiser** [comment]
Hi. Inkscape, for example allows adding effects and modifications to several selected layers and saving each layer of a single svg file in separate files. Furthermore, while the animated svg format is excellent, few programs import it. Be it to continue the composition and additional arrangements in other programs.

**Comment by mestaritonttu** [comment]
I guess an argument could be made that some post-processing software like [Natron](https://natrongithub.github.io/) could be used to apply various effects and colour manipulations. I'm not sure if it supports loading a sequence of SVGs, though. It does support [working with SVGs](https://natron.readthedocs.io/en/rb-2.3/guide/tutorials-svgworkflow.html).

**Comment by faridosc** [comment]
Sorry folks but I have never heard of using SVG sequences... neither of a postprocessing workflow with SVG... 

You can use OpenEXR, otherwise stick with JPG or PNG.

**Comment by mestaritonttu** [comment]
> Sorry folks but I have never heard of using SVG sequences... neither of a postprocessing workflow with SVG...
> 
> You can use OpenEXR, otherwise stick with JPG or PNG.

Indeed, just trying to play devil's advocate. I would close as WONTFIX.
