### ISSUE TITLE
Right to left languages

### ISSUE THREAD

**Issue by zakaria-chahboun** [MaurycyLiebner/enve#154]
Hi, enve animation is a great software especially on Linux, so thank you very much 💙
The problem is I can't write in Arabic language which is a RTL direction.

**Comment by MaurycyLiebner** [comment]
You can enable basic RTL support from settings. #102

![154](https://user-images.githubusercontent.com/16670651/84376844-fedb5600-abe1-11ea-8578-40d6a85444c4.png)
