### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AlexKiryanov** [MaurycyLiebner/enve#160]
Good day! Question on expressions.
I’m doing the same thing as in the video on your channel. https://www.youtube.com/watch?v=vVtJQw12k7U But the program writes an error. Sorry again if stupid question. https://drive.google.com/file/d/1wfeq9KrK6ia14hOF2KM049KD1-lLtvqV/view?usp=sharing

**Comment by MaurycyLiebner** [comment]
**Circle** has a property called **transform** which contains a property **translation**, which has an **x** component.
Correct:
`$cx0 = Circle.transform.translation.x`

**Comment by AlexKiryanov** [comment]
Sorry. But it doesn’t work like that! (
Maybe somewhere else i need to write!?
![1](https://user-images.githubusercontent.com/65244629/85296574-46979280-b4aa-11ea-81d7-d8cae2b78d68.jpg)
![2](https://user-images.githubusercontent.com/65244629/85296578-47302900-b4aa-11ea-850a-3c57d6f9ad1f.jpg)

**Comment by MaurycyLiebner** [comment]
Do not use the **$**.

**Comment by AlexKiryanov** [comment]
Wow! Super! Now the problem with return.
![3](https://user-images.githubusercontent.com/65244629/85297571-9460ca80-b4ab-11ea-9b38-23d90f82c04a.jpg)
Forgive me if I write nonsense.

**Comment by MaurycyLiebner** [comment]
You have to return the desired value from "Calculate" portion of the script (the second text field), e.g., `return cx0;`.

**Comment by AlexKiryanov** [comment]
Works! Thank you very much! Forgive me again if I distract you very much.
And thanks for the program! Honestly, I have long been waiting for something similar.
