### ISSUE TITLE
Flip book does not work in a link scene

### ISSUE THREAD

**Issue by AlexKiryanov** [MaurycyLiebner/enve#163]
Windows 64, ver. a757ba2 2020-06-22
Good day! When working with the flip beech option, a problem appeared.
If this option was implemented in the link scene, then this function does not work.'
https://drive.google.com/file/d/1g12sn9psj7EW1iXdW08bVS8DjCdGKdmC/view?usp=sharing

**Comment by MaurycyLiebner** [comment]
Thank you for reporting these bugs. I will try to fix them soon.

**Comment by AlexKiryanov** [comment]
nothing) Thank you!

**Comment by AlexKiryanov** [comment]
Super! Super! Super! Thank! I don’t know how you do all this! Magic!
But it's great!

ср, 24 июн. 2020 г. в 17:53, MaurycyLiebner <notifications@github.com>:
