### ISSUE TITLE
Visibility Range issue

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#166]
When I want to adjust the Visibility Range of an object on timeline and I drag it to desired position it moves also the keyframes. The keyframes should not be moved, right?

See video: [visibility range vid1.zip](https://github.com/MaurycyLiebner/enve/files/4832389/visibility.range.vid1.zip)

**Comment by MaurycyLiebner** [comment]
They should.

**Comment by dadoprom** [comment]
Oh, ok, I see now... sorry :+1:
