### ISSUE TITLE
[bug] The loop option doens't repeat the sounds

### ISSUE THREAD

**Issue by calogerogigante** [MaurycyLiebner/enve#169]
When you put an audio file in a scene : when you play the animation with the loop enabled, it plays the sound only once.

**Comment by EdisonMuniz** [comment]
I found the same bug.

**Comment by MaurycyLiebner** [comment]
That's more of a missing feature than a bug.

**Comment by calogerogigante** [comment]
When you repeat an animation : it must repeat the sound associated with the animation, no ? Otherwise, it's not usefull to have a loop button because I need to clic again the play button to hear the sound several time ?
For me, it's a bug, not a missing feature, as soon as you have added the loop option...
