### ISSUE TITLE
Request a new feature. Dummy object

### ISSUE THREAD

**Issue by AlexKiryanov** [MaurycyLiebner/enve#173]
Good evening! This is of course a trifle, but is it possible to add such an object? So that he has all the properties of the transformation (translation, rotaton, scale, shear, opacity) but is not visible when rendering?
Thank you so much!

**Comment by MaurycyLiebner** [comment]
What would be the example use of a dummy object?

**Comment by AlexKiryanov** [comment]
good day! Well, for example, as in a project with a camera. A dummy
object is a control object. and it will not need to be disabled when
rendering a video


вт, 30 июн. 2020 г., 12:24 MaurycyLiebner <notifications@github.com>:

**Comment by MaurycyLiebner** [comment]
Yes, I guess that could be useful.

**Comment by AlexKiryanov** [comment]
Thank you so much! Or with a rig a character or whatever.

вт, 30 июн. 2020 г. в 13:19, MaurycyLiebner <notifications@github.com>:

**Comment by Jose-Moreno** [comment]
From your description this is what would be called a "null object" in After Effects or an "empty" in Blender right?

That would certainly be super useful when generating different parenting configurations between objects to help group complex motions 👍

**Comment by AlexKiryanov** [comment]
Jose-Moreno Yes. Exactly!

**Comment by calogerogigante** [comment]
It can be usefull too when you use FLIP BOOK. Sometimes, you want to display nothing, but it's not possible to specify an index who display nothing. If I can add a "empty" in the filp book list, then I can manage when I want to display nothing from the list referenced by the flip book... So, good idea...

**Comment by AlexKiryanov** [comment]
Hey. You can put transparent object in a group. so you can portray
nothing in a flip book)


сб, 4 июл. 2020 г., 11:44 Calogero GIGANTE <notifications@github.com>:

**Comment by calogerogigante** [comment]
Yes, exact.
