### ISSUE TITLE
Split timeline bug

### ISSUE THREAD

**Issue by AlexKiryanov** [MaurycyLiebner/enve#174]
Good evening!
I found such a strange thing.
If at work, I split timeline vertically or horizontally. Then I close the first timeline.
And after that, the slider and animation stops working. More precisely, the animation is played, but it does not respond to the slider.
video https://drive.google.com/file/d/1-ybTcZaddk4Zi50gYuQ7CObFN2rRAtO8/view?usp=sharing
Thank you so much!

**Comment by dadoprom** [comment]
You have to select the scene or set it to active.
![scene](https://user-images.githubusercontent.com/19377506/86061224-a96aca00-ba66-11ea-8b25-4de83308a49f.png)

**Comment by AlexKiryanov** [comment]
Thank you so much! honestly I didn’t even intuitively understand that
something needs to be switched) now I understand)

вт, 30 июн. 2020 г., 01:15 dadoprom <notifications@github.com>:
