### ISSUE TITLE
Question. Where did the sculpting tool go?

### ISSUE THREAD

**Issue by AlexKiryanov** [MaurycyLiebner/enve#178]
Win 10 64bit ver enve 01.07.2020
Hello! Can't find this tool in the panel?
Thank! And a good day)

**Comment by MaurycyLiebner** [comment]
It was removed. It wasn't all that useful. #170

**Comment by AlexKiryanov** [comment]
Thanks for the answer!)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пт, 3 июл. 2020 г. в 14:40, MaurycyLiebner <notifications@github.com>:
