### ISSUE TITLE
Program logo in curvs

### ISSUE THREAD

**Issue by AlexKiryanov** [MaurycyLiebner/enve#179]
Good afternoon, you can download the logotype of the program in curve, so as not to draw it myself)
I want to do a lesson, and I need it for animation.
Thank you so much.)
Have a nice day)

**Comment by MaurycyLiebner** [comment]
You can download the following file and rename it to enve.svg:
https://raw.githubusercontent.com/MaurycyLiebner/enve/master/src/app/icons/enve

**Comment by AlexKiryanov** [comment]
Thank you so much!))

сб, 4 июл. 2020 г. в 14:56, MaurycyLiebner <notifications@github.com>:
