### ISSUE TITLE
Not all edit functions work

### ISSUE THREAD

**Issue by beef331** [MaurycyLiebner/enve#19]
On Ubuntu 19.10, using the undo,cut, and delete shortcuts, or manually clicking does not work.

**Comment by MaurycyLiebner** [comment]
As of right now, enve does not support undo/redo.
I will implement it soon(ish), after I clean up the code.

Cut and delete seem to work for me.
Cut, copy and paste are for objects only, meaning you cannot use it with, e.g., nodes.
I checked 'delete' on path nodes, and there is a small problem, it does not apply the action until other action is performed, I will fix it in a minute.
The relevant actions should get disabled/enabled when they can be used, that's a missing feature.
Is the issue you are experiencing contained in what I described, or is it something else?

**Comment by beef331** [comment]
So it's currently not possible to undo drawn lines?

**Comment by prokoudine** [comment]
@beef331 it's not possible to undo anything right now :)
