### ISSUE TITLE
Initializing GL functions failed

### ISSUE THREAD

**Issue by Symbian9** [MaurycyLiebner/enve#2]
- **Version:** `0.0.0` (release; AppImage)
- **OS:** Debian 9.x (x86_64)
- **GPU**: ATI Radeon 1250 Xpress
  - OpenGL Version 2.1 Mesa 13.0.6 (GLSL 1.20)
  - Gallium 0.4 on ATI RS600 - X.Org R300 Project

### Actual behavior

*enve* execution aborted:

![pic.1](https://i.imgur.com/hDZGk44.png)

### Expected behavior

*enve* should run as expected

### Terminal Log

```
$ ./enve-0.0.0-x86_64.AppImage
0)  42  :  offscreenqgl33c.h  :  makeCurrent()
  Initializing GL functions failed.
terminate called after throwing an instance of 'std::_Nested_exception<std::runtime_error>'
  what():  42  :  offscreenqgl33c.h  :  makeCurrent()
  Initializing GL functions failed.
Aborted
```

**Comment by MaurycyLiebner** [comment]
As of right now, enve requires OpenGL 3.3.
The error message should probably point to that, as it could be a common problem.

**Comment by Symbian9** [comment]
> enve requires OpenGL 3.3.

Does it happen because *enve* require OpenGL 3.3 for blending modes? Could it be solved in any way?

As I know *Olive* app has special mode (`$ ./Olive*.AppImage --disable-blend-modes`) especially for running on older GPU

- https://github.com/olive-editor/olive/commit/1212405046f63205f133063f3795f349d6a596c4
  - https://github.com/olive-editor/olive/search?q=blend+modes&type=Commits

**Comment by MaurycyLiebner** [comment]
I will look into this.

**Comment by MaurycyLiebner** [comment]
I am afraid it cannot be done. The oldest OpenGL version enve (maybe) could support is 3.0.
Enve relies on many newer OpenGL features ex. Vertex Array Objects, Framebuffer Objects.
