### ISSUE TITLE
Total System Crash Using Enve on Archlinux and Wine

### ISSUE THREAD

**Issue by Gilraiser** [MaurycyLiebner/enve#208]
Both the appimage in archlinux, and the windows executable in wine generate a total system failure. It was tested in the gnome boxes virtual machine, there it does not generate the total archlinux failure, but it does break the program. I think it may be ram mismanagement or opencl incompatibility. Is there any way to compile enve without opencl?

thanks.

**Comment by zakaria-chahboun** [comment]
just use latest appimage version, if you want to use `wine` for test, just use windows!

**Comment by Gilraiser** [comment]
Apparently Enve doesn't work if the driver doesn't support OpenCL in linux. I have switched to the official Nvidia drivers and installed Pulseaudio. The program works fine now. Before I used linux xf86-video-nouveau.
