### ISSUE TITLE
Imported image sequence loop

### ISSUE THREAD

**Issue by mokalux** [MaurycyLiebner/enve#214]
Is it possible for an imported image sequence to loop? I haven't found this possibility.

The solution I found was to copy paste the image sequence all along the timeline.

**Thank you for making enve :-)**

**Comment by AlexKiryanov** [comment]
Hello, https://youtu.be/T87bfig8qVU this video help you)

**Comment by mokalux** [comment]
thank you AlexKiryanov I have watched your videos before posting ;-)

I wanted something a bit different, that is having my image sequence to auto-loop and only have to deal with its position in the timeline.

Right now I can either copy multiple instance of my image sequence and put them in a group so I can position the group.

Or I can create multiple key frames for the frame remapping.

Both are a little bit long :-(

I will close the issue for now. Once again thank you for your reply.
