### ISSUE TITLE
Enve crash after croping drawn image in "Paint mode"...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#215]
Enve crash after cropping drawn image in "Paint mode"...

Crash Scenario nr.1
1. draw something in "Paint mode" with the default deevad pencil brush
2. select crop tool and crop the drawn image
3. while crop tool still active click outside the drawn image on the canvas > Enve crash

Crash Scenario nr.2
1. draw something in "Paint mode" with any other brush
2. select crop tool and crop the drawn image
3. while crop tool still active click outside the drawn image on the canvas > the cropped painting disappear
4. select another tool from the tools panel, for example, "Select tool" (Object mode) > Enve crash

**Comment by MaurycyLiebner** [comment]
Thank you. Should be fixed when the next release comes out.

**Comment by dadoprom** [comment]
Thank you :)
