### ISSUE TITLE
Enve closes when I play the animation.

### ISSUE THREAD

**Issue by Gilraiser** [MaurycyLiebner/enve#220]
**System Information**
**Operating system:** Archlinux x64
**Linux kernel:** lts
**graphic card:** nvidia gt 610
**driver:** nvidia-390xx-dkms 390.141-2
opencl-nvidia-390xx 390.141-1
**Enve version:** continuous build linux 03/05/2021

**Issue description**

Kind regards to you Enve developers. The program closes when you click the play button or the loop button. This happens with all forms of graphics, whether they are imported or drawn with nodes or raster.

This is displayed in the terminal:

./enve.AppImage
Entered main()
Setup Default QSurfaceFormat
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Hardware:
    CPU Threads: 4
         Memory: 11913MB
            GPU: Nvidia

Generated Alpha Mesh
Loaded settings
QIODevice::read (QFile, "/home/unleashed/.enve/icons/18/ver"): device not open
Entered initializeGpu
OffscreenQGL33c initialized
Make OffscreenQGL33c current
iniPlainVShaderVBO
iniPlainVShaderVAO
iniTexturedVShaderVBO
iniTexturedVShaderVAO
iniColorPrograms
Done OffscreenQGL33c current
Entered GpuExecController initialize
GpuTaskExecutor initialized
Entered GpuTaskExecutor::initializeContext
Created GrGLInterface
Created GrContext
iniTexturedVShaderVAO
SwitchableContext set
Done GpuTaskExecutor::initializeContext
Custom path effects initialized
Custom raster effects initialized
Shader effects initialized
Custom objects initialized
PulseAudioService: pa_context_connect() failed
Using:
    Sample rate: -1
    Channel count: -1
    Sample size: -1
    Codec: 
    Sample Type: 0
    Byte order: 1
0)  46  :  audiohandler.cpp  :  toAVAudioFormat()
  Unsupported sample format 0
Audio initialized
QObject::connect(QAudioOutput, RenderHandler): invalid null parameter
Render handler initialized
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
Violación de segmento (`core' generado)

**Thank you for your attention and for developing Enve.**

**Comment by MaurycyLiebner** [comment]
It looks like an audio issue. It may not be related to enve itself, but to pulseaudio.

See: https://www.google.com/search?q=PulseAudioService%3A+pa_context_connect
Apologies for giving you a google search as an answer, but I am not sure which will work for you. There are some Archlinux related answers.

**Comment by Gilraiser** [comment]
Hello, thanks for answering @MaurycyLiebner . I don't have Pulseaudio installed, I only have Alsa installed. Would I have to install it for Enve to work properly?

**Comment by MaurycyLiebner** [comment]
Honestly, I don't know much about sound systems. Based on the results of the google search, I think PulseAudio is necessary.

**Comment by Gilraiser** [comment]
Ok, thank you very much, it already works.
