### ISSUE TITLE
Text effect diminish widget not displayed

### ISSUE THREAD

**Issue by samytichadou** [MaurycyLiebner/enve#228]
Windows 10
enve_3_11_21

Hi, i tried to animate some text effect, but the diminish wiggle is not available. Changing values seem to work, but it is hard to use them without visual cue.

Cheers

**Comment by MaurycyLiebner** [comment]
It should be visible in point editing mode (F2). Does it solve your problem?

**Comment by samytichadou** [comment]
Yes works perfectly, sorry didn't know i have to be in point mode to see it ! 
Thanks for the quick reply ! cheers
