### ISSUE TITLE
When import svg...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#23]
When import svg the naming of paths is always "path" even if there is like 50 of them... same goes for "circle" and "rectangle" and "text"... I think the paths, circles, rectangles and texts should have unique names by default - it should not be all the same...

for example- path1, path2, path3, text12 and so on... than it is more easy to work with it even without manual renaming objects...

![naming-objects](https://user-images.githubusercontent.com/19377506/71482743-75d38c80-2804-11ea-9d4f-bcdc7242b95f.png)

**Comment by dadoprom** [comment]
also "group" should be group1, group2, etc.

**Comment by MaurycyLiebner** [comment]
You are correct. This is also true for user created objects (paths, groups etc.).

**Comment by dadoprom** [comment]
Yes, also user created objects...

**Comment by gromain** [comment]
Also, for renaming, double-click on the name or F2 once selected would make it easier than right click then rename.

**Comment by dadoprom** [comment]
Good job... I think the first object should be "Object 0" rather than "Object"...
This numbering is correct: "Object 0",  "Object 1",  "Object 2",  "Object 3",  "Object 4"...
This is numbering is natural/human: "Object 1",  "Object 2",  "Object 3",  "Object 4"...
But this not-numbering/numbering feels confusing: "Object",  "Object 1",  "Object 2",  "Object 3",  "Object 4"...

And also, there is a bug when renaming object with names containing numbers... If I want to rename "Object 2" to "Object 6" enve renames it to "Object 3" instead beacause that is the first auto naming name that it is not taken or exist... or something like that... and than it behaves even stranger when you re-number one particular object multiple times - the numbering goes up or down...

**Comment by dadoprom** [comment]
There is one more issue I noticed: watch the video in zip...

[numbering_issue.zip](https://github.com/MaurycyLiebner/enve/files/4150383/numbering_issue.zip)

Also I think user should be able to have multiple objects with the same name and number (they will expect it to be possible)... now it is possible to have it like this: circle1 circle 1, should be also possible to have circle 1 and circle 1
