### ISSUE TITLE
Non-linear tweening

### ISSUE THREAD

**Issue by astrosticks** [MaurycyLiebner/enve#234]
Hi! Apologies if this exists already, but I can't seem to find an option to change the interpolation method between keyframes. Just lerp isn't doing it for me.

**Comment by AlexKiryanov** [comment]
Hey! You can change the interpolation in the curve editor. Click this button.
![1](https://user-images.githubusercontent.com/65244629/116060037-2a482180-a68a-11eb-9ac0-9f711c9a0fd5.jpg)
Do not forget to select the desired parameters that you want to be displayed in the curve editor.
![2](https://user-images.githubusercontent.com/65244629/116060042-2ae0b800-a68a-11eb-8aaa-cc316153ed51.jpg)
Select the animation key and change the interpolation with these buttons. Linear. Bezier curves. Divided bezier curves.
![3](https://user-images.githubusercontent.com/65244629/116060044-2ae0b800-a68a-11eb-86dd-d2e6710a78ba.jpg)

**Comment by flurick** [comment]
In the latest version as of writing this it seems like you also have to at least click the points/keyframes to get them to update to the new type  you select.

**Comment by AlexKiryanov** [comment]
I didn't exactly understand what you wrote, so I could be wrong with the answer.
Yes, before specifying interpolation for a key, you need to select it. But I thought that these are self-evident things and did not focus on it.

**Comment by astrosticks** [comment]
@AlexKiryanov oh thank you! I guess I need to get used to using this, but from trying it out myself, it seems slightly tedious to "draw" the interpolation paths manually, esp. when all I might want are a specific consistent interpolation between each keyframe. But clearly that's outside the scope of this issue, so I'll close it.
