### ISSUE TITLE
Add keyframe for current frame

### ISSUE THREAD

**Issue by schuettec** [MaurycyLiebner/enve#239]
Is it possible to create an explicit keyframe between to existing ones? I have an animation that is perfect for the first half of the duration between two keyframes. I want to keep the first half of the animation and drop the rest. How can I do this?

Btw: Thanks for this great work. I really like enve and I learned a lot with your Youtube videos in the past 3 days :+1: Thanks!

**Comment by dadoprom** [comment]
Hi, see the video...
https://user-images.githubusercontent.com/19377506/118277988-be5b1b00-b4c9-11eb-8dd7-76776defda4d.mp4

**Comment by schuettec** [comment]
Ha, awesome! Thanks!!!
