### ISSUE TITLE
Dragging text crashes enve

### ISSUE THREAD

**Issue by Bernd-L** [MaurycyLiebner/enve#24]
# Dragging text crashes enve

## Steps to reproduce

1. Click the text tool
2. Click somewhere
3.  Enter text
4. OK
5. Click & drag from within the fill of a letter
6. Wait
7. Crash

## Info

Key|Value
-|-
Kernel|`5.4.2-1-MANJARO x86_6`
Distro|Manjaro GNOME
Enve version|`0.0.0` AppImage (the one on the GitHub releases)

**Comment by MaurycyLiebner** [comment]
Do you have an Nvidia GPU? (look #6)

**Comment by MaurycyLiebner** [comment]
You should try the current continuous build.
GPU path rendering acceleration is disabled by default for Nvidia GPUs (Edit -> Settings...).
You cannot disable it in enve 0.0.0.

**Comment by Bernd-L** [comment]
@MaurycyLiebner The newest version 50b47ee does not have this issue; closing
