### ISSUE TITLE
Path effects are not exported - Svg export

### ISSUE THREAD

**Issue by adambelis** [MaurycyLiebner/enve#242]
## steps to replicate
1. create a path (line)
2. add any random subpath effect (subpath)
3. Animate  values of path effect
4. export to SVG

## Result
 no animation  is exported

## Expected
the animation  should be exported

## Workaround

if I add keyframes to the path attribute at the beginning and end of the timeline (same value) 
animation gets exported

## System

win 10 
enve5_14_21

**Comment by adambelis** [comment]
thank you for fixing this  .. cannot test coz iam big noob that cannot compile anything will test in tex release :D

**Comment by MaurycyLiebner** [comment]
A new release is already available. :)

**Comment by adambelis** [comment]
OH you have an auto builder cool !
 just tested and can confirm this **fixed it** 
 Only side note is  that if i open the old project project it does not get exported properly.
 but if i creat new project it works  fine .
 thanks again for fixing it

**Comment by Ahmed-elshorbagy** [comment]
i think the bug still exists
thanks in advance
