### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by santos89ers** [MaurycyLiebner/enve#248]
First, I want to thank you for this awesome software and your hard work

Now the problem, I tried the latest Windows build (5_20_21 on its file name), My PC spec are Windows 10, Pentium G2030, 4GB Ram, Nvidia GeForce 1030, and found some issue with rendering

1. I have some shape that i've imported from Inkscape SVG file
2. Do some simple animation (moving, fading, scaling)
3. Click on play button (render preview)
4. Some of my shape not showing, some of it change its color to gray or black (happend at few last frame)
5. When I render to video (mp4) that anomalies carried out, but when I export to SVG, everything seem normal.
6. Tried to change to CPU rendering, it has no issue at preview, I think I found the solution...
7. But, it stop render when reach the final frame, it stuck and took up nearly 1 GB of my RAM

Any workaround or fix to these issue are appreciated, Regards

**Comment by MaurycyLiebner** [comment]
4. I have no problems with my AMD GPU. Probably a Nvidia specific driver issue. Disabling "Path GPU acceleration" is the best I can do, since I do not own any Nvidia GPU.
7. Could you share the example file that doesn't finish rendering?

**Comment by dadoprom** [comment]
These settings work for me on AMD GPU... 

![image](https://user-images.githubusercontent.com/19377506/120501931-4c883a00-c3c2-11eb-8e8f-1bb78e01dcea.png)


and for the rendering, just run it again... sometimes it gets stuck... just run it again and it will be ok

**Comment by AlexKiryanov** [comment]
By the way, I noticed that when I have a lot of programs open and there is little RAM left, then yes, ENVE does not render. In this case, I just close all programs to free up RAM and everything works fine.

**Comment by santos89ers** [comment]
https://user-images.githubusercontent.com/50803207/120650276-d0682200-c4a7-11eb-8a31-fa385674c39e.mp4

[render issue.zip](https://github.com/MaurycyLiebner/enve/files/6591854/render.issue.zip)


here is the files @MaurycyLiebner, sorry for the late reply

**Comment by santos89ers** [comment]
https://user-images.githubusercontent.com/50803207/120651771-5173e900-c4a9-11eb-8b8c-8769a6098eb6.mp4

here I recorded the process to make above files

**Comment by AlexKiryanov** [comment]
[gsdgasdg new.zip](https://github.com/MaurycyLiebner/enve/files/6592145/gsdgasdg.new.zip)
Here I fixed your file.
1. No need to create animation keys for properties of objects that are not used. This is superfluous information.
I have cleared some, but not all.
2. The problem was solved by combining the letters in the inscriptions kabupaten and pasuruan into one figure (command Ctrl + K).

**Comment by MaurycyLiebner** [comment]
I could duplicate the issue with artifacts (4) on Windows, it does not occur on Linux. I did not do much testing for the Windows version, it seems slower and generally less stable.

**Comment by santos89ers** [comment]
> [gsdgasdg new.zip](https://github.com/MaurycyLiebner/enve/files/6592145/gsdgasdg.new.zip)
> Here I fixed your file.
> 
> 1. No need to create animation keys for properties of objects that are not used. This is superfluous information.
>    I have cleared some, but not all.
> 2. The problem was solved by combining the letters in the inscriptions kabupaten and pasuruan into one figure (command Ctrl + K).

Thank you for your advice and fixes, I'll inform here as soon as i can,

**Comment by santos89ers** [comment]
> I could duplicate the issue with artifacts (4) on Windows, it does not occur on Linux. I did not do much testing for the Windows version, it seems slower and generally less stable.

Seem I'll use @AlexKiryanov workaround for now, thank you.

**Comment by santos89ers** [comment]
![setting](https://user-images.githubusercontent.com/50803207/120820338-a46ba000-c57e-11eb-9dae-5ac4a6c0a374.png)

I change the setting to this, and it seems working fine for now. once again thanks for your great help @MaurycyLiebner and @AlexKiryanov , and @dadoprom for the response, thank you. I hope enve2D will be great software at the future.
