### ISSUE TITLE
need constant interpolation (HOLD) keyframe in graph editor

### ISSUE THREAD

**Issue by rbjnazz** [MaurycyLiebner/enve#252]
I can't make a constant keyframes (HOLD) using the graph editor
example:
![dBGOQ](https://user-images.githubusercontent.com/85556041/121174271-f0229000-c883-11eb-8afd-0262ad09847a.png)

**Comment by AlexKiryanov** [comment]
Good afternoon, this question was already in #176.

**Comment by AlexKiryanov** [comment]
Not. Unfortunately.( But I would also like to have such a function
I wrote to you not to make copies of the requests.

**Comment by rbjnazz** [comment]
Thanks for clearing things up. Gonna close this issue.
Hoping for this function soon
