### ISSUE TITLE
Program crashed | in first running, look like gpu, mesa or open gl problem

### ISSUE THREAD

**Issue by Luneriazz** [MaurycyLiebner/enve#253]
**My Laptop Spec :**

OS: Manjaro Linux x86_64 
Host: Aspire A315-42 V1.10 
Kernel: 5.12.8-1-MANJARO 
Uptime: 4 hours, 22 mins 
Packages: 1803 (pacman), 31 (flatpak), 13 (sn 
Shell: bash 5.1.8 
Resolution: 1366x768 
DE: Plasma 5.21.5 
WM: KWin 
WM Theme: McMojave 
Theme: McMojave [Plasma], Breath-Dark [GTK2/3] 
Icons: McMojave-circle-dark [Plasma], McMojave-circle 
Terminal: konsole 
Terminal Font: Noto Mono 10 
CPU: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx (4 
GPU: AMD ATI 04:00.0 Picasso 
Memory: 3490MiB / 5943MiB

My Open GL version :
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon(TM) Vega 3 Graphics (RAVEN, DRM 3.40.0, 5.12.8-1-MANJARO, LLVM 11.1.0)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.1.2
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.1.2
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Enve appimage Log from terminal :**

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Entered main()
Setup Default QSurfaceFormat
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_enve-avLMin6/usr/optional/libstdc++/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /tmp/.mount_enve-avLMin6/usr/optional/libstdc++/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /tmp/.mount_enve-avLMin6/usr/optional/libstdc++/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: swrast
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
QGLXContext: Failed to create dummy context
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 453, resource id: 0, major code: 152 (Unknown), minor code: 24
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 485, resource id: 0, major code: 152 (Unknown), minor code: 24
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 663, resource id: 0, major code: 152 (Unknown), minor code: 24
0)  Creating OpenGL context failed.
 Make sure your GPU drivers support OpenGL 3.3 core.
Hardware:
    CPU Threads: 4
         Memory: 5943MB
            GPU: Unrecognized

Generated Alpha Mesh
Loaded settings
Entered initializeGpu
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 1002, resource id: 0, major code: 152 (Unknown), minor code: 24
0)  Creating OpenGL context failed.
 Make sure your GPU drivers support OpenGL 3.3 core.
terminate called after throwing an instance of 'std::_Nested_exception<std::runtime_error>'
  what():  Creating OpenGL context failed.
 Make sure your GPU drivers support OpenGL 3.3 core.
 
 report problem. this problem appear after i update my manjaro.
 look like mesa problem.
 
 is there solution for this?

**Comment by MaurycyLiebner** [comment]
https://forum.manjaro.org/t/many-appimages-have-stopped-working-after-todays-update/69445

**Comment by Luneriazz** [comment]
> It doesn't seem like an enve issue.
> https://forum.manjaro.org/t/many-appimages-have-stopped-working-after-todays-update/69445
thanks for reply...
after install the flatpak version its working normal...
