### ISSUE TITLE
No shortcut for erasing

### ISSUE THREAD

**Issue by Flairieve** [MaurycyLiebner/enve#254]
The eraser tool for Paint Box objects does not have a keybind for it or its not documented.
This makes it hard for users to erase their lines when they are using a Draw Tablet or a Graphics Tablet.

I think the Eraser shortcut should be E though this shortcut is already being used by the Fill and Stroke menu.
Thanks!

**Comment by irwant** [comment]
![Screenshot from 2021-06-12 15-40-46](https://user-images.githubusercontent.com/10395887/121770634-9926fe80-cb94-11eb-90f4-6f3a7b461179.png)
the tool for paint

**Comment by AlexKiryanov** [comment]
good evening! To be honest, this is not a bad idea! If Maurycy doesn't mind, I can change and add some hotkeys. 
Let's assume.
For brush mode - set the brush shortcut B
For erase mode, hotkey E
Therefore, for the dock of the Brush, I will change the key to Ctrl + B
For dock Fill and sroke Ctrl + e
Same. Do you think you need to add hot keys for the other 2 brush modes? I mean Look alpha and Colorize.
@MaurycyLiebner Can I do it?

**Comment by Flairieve** [comment]
Not really for me right now I guess but for other people it might help as well.

**Comment by MaurycyLiebner** [comment]
> @MaurycyLiebner Can I do it?

@AlexKiryanov Sure.
