### ISSUE TITLE
Path Changes don't work correctly

### ISSUE THREAD

**Issue by NothingAnimated** [MaurycyLiebner/enve#259]
So I was trying to make a simple motion graphic and one of the shapes I needed required for the shape to be hollowed out. So I tried doing that with the red shape and did the difference modifyer as seen here
![image](https://user-images.githubusercontent.com/69369888/122282146-131ef680-ceb9-11eb-9e80-666d909e4b47.png)
but when I do it it doesn't do anything (even when I convert the objects into a path)
So I decided to do it in inkscape as seen here:
![image](https://user-images.githubusercontent.com/69369888/122282901-f2a36c00-ceb9-11eb-9210-7275c87c80a9.png)
And after doing it it look like this
![image](https://user-images.githubusercontent.com/69369888/122283007-15358500-ceba-11eb-9c32-10b037581e6d.png)
But then after importing it into enve it doesn't show up but the layer is there. So that means the path modifiers are broken and don't work. Is there a fix for this?

**Comment by AlexKiryanov** [comment]
Good evening! After the boolean operation, go to the properties of the path object and change the value in this scroll to Even-odd
![image](https://user-images.githubusercontent.com/65244629/122287619-cf98ac80-cef9-11eb-8164-cf152d8c4150.png)
Also, pay attention to the fact that the object to be subtracted must be under the object from which the object is subtracted.

**Comment by NothingAnimated** [comment]
Ok that fixed it thank you

**Comment by AlexKiryanov** [comment]
Hello. Your welcome) please close the issue.
