### ISSUE TITLE
Missing icons in save dialog...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#26]
Missing icons in save dialog... see image...

![missing-icons](https://user-images.githubusercontent.com/19377506/71489597-9f051480-2826-11ea-9341-38497a2134e4.png)

**Comment by MaurycyLiebner** [comment]
Enve should use native dialogs. The issue is related to the way Qt works and the current Travis CI AppImage deployment script. Solution coming soon.

**Comment by MaurycyLiebner** [comment]
Could you test the current continuous build on your setup?
Some UI elements are broken, but enve uses native dialogs?

**Comment by dadoprom** [comment]
With enve-8755040-x86_64.AppImage build I have the same old dialogs - no change...

![enve-old dialogs](https://user-images.githubusercontent.com/19377506/71521398-e8a23d80-28c0-11ea-891b-cc0581723df6.png)

**Comment by MaurycyLiebner** [comment]
I have native dialogs with xfce, probably because it's gtk based.
I guess KDE requires additional libraries.

**Comment by MaurycyLiebner** [comment]
In ~40 minutes there should be a new continuous build, would be grateful if you would check how the dialogs look like on your system.

**Comment by dadoprom** [comment]
It is ok now, looks perfect, thanks :)

![dialogs](https://user-images.githubusercontent.com/19377506/71529644-0209b080-28e6-11ea-8d02-fd6b25127373.png)
