### ISSUE TITLE
Unable to Drag & Drop SVG file made with InkScape or Affinity Designer!

### ISSUE THREAD

**Issue by mbennette68** [MaurycyLiebner/enve#261]
Hello,

I crated a few SVGs, mostly, from the icon found in the, windows version, of the Enve Executable.
I can't seem to drag the file into Enve, nor import it from the File Import menu. 
I was able to import a PNG version of the same icon converted file, then export that as an SVG from Enve.
That version of the SVGwas draggable into Enve but as a square box where the image was not present.

I am using Windows 10 64-bit and Enve 6.11.21 but I had the same issue with Enve 4.26.21. I tried creating SVGs with other software but experience similar errors. The only thing I've done different with Enve is that I extracted the software into a portable folder and ran it from there rather than installing it.

Any thoughts would be appreciated
[enve_svgs.zip](https://github.com/MaurycyLiebner/enve/files/6698447/enve_svgs.zip)

**Comment by AlexKiryanov** [comment]
Good day! Why did you insert a raster image into the svg file? and then trying to port it as vector?
Of course, in this case, you will not succeed.
Easier to import the png file directly into the program.
If you need a vector logo for Enve then here you are!
[enve.zip](https://github.com/MaurycyLiebner/enve/files/6701885/enve.zip)

**Comment by AlexKiryanov** [comment]
good evening! I'm not Maurycy) if you have no more questions, please close the topic
