### ISSUE TITLE
What Does This Option DO?

### ISSUE THREAD

**Issue by mihadalam56** [MaurycyLiebner/enve#264]
hey i just need to know what this clamped option do in the timeline?
![clap](https://user-images.githubusercontent.com/86367188/123906959-f1347200-d996-11eb-9a01-8ca587a5e844.png)

**Comment by AlexKiryanov** [comment]
Good day! This is a not yet implemented feature.

**Comment by AlexKiryanov** [comment]
Honestly, I don't know. But perhaps this will limit the pre-render area according to the visible area of the timeline. In other words: Suppose you have a scene with 200 frames. But the scale of the timeline is such that you can see, for example, from 30 to 100 frames. When this function is enabled, the pre-rendered animation will be in the visible area only. That is, from 30 to 100 frames.
But I could be wrong.)))

**Comment by mihadalam56** [comment]
Ohh :) Thank you
Can you add seconds to the timeline?
Its kinda confusing just to work with frames :(

**Comment by AlexKiryanov** [comment]
I cannot, unfortunately, agree this is a very useful function. But I was able to add the count of frames in seconds in the scene settings.

**Comment by mihadalam56** [comment]
Ohh, thanks for the seconds counter in scene setup
And lets just hope that the developer will add this in future 😇❤️

**Comment by AlexKiryanov** [comment]
Yes! Let's hope)

**Comment by AlexKiryanov** [comment]
If there are no more questions, please close the issue.
