### ISSUE TITLE
Expression for Objects?

### ISSUE THREAD

**Issue by mihadalam56** [MaurycyLiebner/enve#268]
Hey! 
Can Anyone Give Me Some Expression 
I need these expressions:
Wiggle
Loop

Also can You Tell Me How They Work.
I Don't Understand Expression At all :(

**Comment by AlexKiryanov** [comment]
Hello! This is for loop expression.
https://youtu.be/T87bfig8qVU 
But ... There is one problem with the loop. If you make a loop for the link scene, then an error occurs when mixing this scene. When the cycle starts over, the scene moves back to the starting position. Unfortunately this bug has not been fixed yet.

**Comment by mihadalam56** [comment]
Thanks but do you have wiggle expression?

**Comment by 2439905184** [comment]
Do some people have written some articles to help others learn expressions ?
Offical website(enve) do not have this type of tutorial.

**Comment by 2439905184** [comment]
Or give a tip about difference between Adobe AfterEffects's expression and enve's expression.
