### ISSUE TITLE
Go to frame 0 button...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#27]
Go to frame 0 button... I think there should be such button on the Timeline... if I quickly want to start playing the animation from the beginning...

At the moment I have to manualy go to frame 0 - this is time consuming...
The behaviour of play/pause and stop button is super...

**Comment by MaurycyLiebner** [comment]
Probably a button that would play from the beginning, instead of the current frame would be a better solution. Good idea.

**Comment by dadoprom** [comment]
I really like the current play/pause and stop buttons behaviour. There just should be added a third button that would do what you suggest.

button nr. 1. play from the begining
button nr. 2. play from current/selected frame (as it is now)
button nr. 3. stop on the selected frame (as it is now)

**Comment by MaurycyLiebner** [comment]
Exactly.
![i27](https://user-images.githubusercontent.com/16670651/71493938-848d6400-2843-11ea-944c-001a9126194d.png)
