### ISSUE TITLE
Expression Error

### ISSUE THREAD

**Issue by mihadalam56** [MaurycyLiebner/enve#275]
Hello,
I was testing the advanced character rig tutorial from Alex's youtube video.
But Im getting an error. I do not know how to code or write expressions.
I have 18 objects in the group and I wanted to control the flipbook with the Control Object.
![error](https://user-images.githubusercontent.com/86367188/128682470-337d21ef-e673-494b-b6ce-b1e0e72967e4.png)

Please tell me what is wrong and how to fix it.

**Comment by AlexKiryanov** [comment]
Hey! Would you like to send me your file, I will look at it and correct it?

**Comment by mihadalam56** [comment]
Thanks, Alex!
Here Is The Project File

[advanced rig test.zip](https://github.com/MaurycyLiebner/enve/files/6959124/advanced.rig.test.zip)

**Comment by AlexKiryanov** [comment]
Hey! Corrected.
[advanced rig test new.zip](https://github.com/MaurycyLiebner/enve/files/6960618/advanced.rig.test.new.zip)

**Comment by mihadalam56** [comment]
Thanx, A Lot!! Alex 
You Are Truly A Pro At Enve.

**Comment by AlexKiryanov** [comment]
you did not use a return command in a condition expression
In other words: you assigned a value to a variable and then the program did not know what to do with it.

**Comment by mihadalam56** [comment]
Ohh,
I Also Noticed That The Expression In The File That Was Slightly Different From Your Youtube Video.
Is It A Big Different?

**Comment by AlexKiryanov** [comment]
The code depends on your task. I don't know exactly what you wanted to do, I just tweaked your code to make it work.

**Comment by mihadalam56** [comment]
So The Code Will Change In Different Cases? 
After You Answer That  I Will Close The Issue :)

**Comment by AlexKiryanov** [comment]
Yes. The code depends on your task. And at the same time, the same task can be solved in several ways.
