### ISSUE TITLE
Loop scene...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#28]
I would like to be able to make a  scene where I could set to loop animation. Lets say I create some small animation with only like 20 frames. Than I would set it to loop. Than I would link this loop animation scene to my main scene... this would save ton of work... So we only need "loop scene" :)

**Comment by MaurycyLiebner** [comment]
It would make more sense to add a checkbox for that in the linking object. Good idea.

**Comment by dadoprom** [comment]
Yes indeed, checkbox is perfect!

**Comment by MaurycyLiebner** [comment]
Looping can be done with expressions. First enable frame remapping from the Scene Link's context menu, then right click on the Frame Remapping value slider. Choose Set Expression and enter e.g.:
50 + $frame % 151
This will make the link loop from 50 - 200.
x % y - value of x that remains after division by y, e.g.,
4 % 2 = 0
5 % 2 = 1
7 % 2 = 1
5 % 3 = 2

**Comment by dadoprom** [comment]
Ok, tested, works perfect... just little complicated to setup :)

**Comment by dadoprom** [comment]
But endless possibilities with these Expressions... just my math sucks :D
