### ISSUE TITLE
How to keyframe visibility?

### ISSUE THREAD

**Issue by schuettec** [MaurycyLiebner/enve#284]
Hi,
I'm very sorry if my question is stupid, but I can't find a way to make object invisible using keyframes. I found "Visibility Range" that enables me to make visible things invisible and vice-versa, but only once. Is there any possibility to keyframe visibility? Like a boolean visibility property?
Opacity would be another way to go, but for a simple switching like visible/invisible/visibile this seems a little bit cumbersome.

Thx for any help!

**Comment by eFe-Munoz** [comment]
Hello Christopher.

One possible way is to use layer modes. The DstIn mode allows the top object above A to hide all the objects below it.  This way if you animate object A with keyframe positions you can create an appear/disappear.

You can find that in this Enve manual in english:

4.6.2. Layer modes, groups and Layers

https://theflydesign.es/manual-enve-04-environment-and-panels/#462

**Comment by schuettec** [comment]
Hi thanks for your answer. This is a possible workaround.
I got one question left: Why do groups not always populate their property values to child objects?
If I group rectangles, text elements or paths, changing the opacity on the group does nothing :/

**Comment by eFe-Munoz** [comment]
I see you haven't read chapter 4.6.2. If you use group effects or layer modes etc... you have to click on the rectangle with stripes to "Promote to Layer".

Once you have done this, try the opacity again.

**Comment by schuettec** [comment]
Yes, got me!
I started with the youtube videos. I saw the manual a few days ago. I close this one. Thanks again for your help! :)
