### ISSUE TITLE
AppImage in Manjaro - symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full

### ISSUE THREAD

**Issue by MiguelMJ** [MaurycyLiebner/enve#289]
I downloaded the AppImage for linux 64bits and after executing it, the console just prints this message:
```
enve: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full
```
I don't think the verison of my library is the problem. Output of `ldconfig -p | grep libgio`:
```
        libgiomm-2.4.so.1 (libc6,x86-64) => /usr/lib/libgiomm-2.4.so.1
        libgiomm-2.4.so (libc6,x86-64) => /usr/lib/libgiomm-2.4.so
        libgio-2.0.so.0 (libc6,x86-64) => /usr/lib/libgio-2.0.so.0
        libgio-2.0.so.0 (libc6) => /usr/lib32/libgio-2.0.so.0
        libgio-2.0.so (libc6,x86-64) => /usr/lib/libgio-2.0.so
        libgio-2.0.so (libc6) => /usr/lib32/libgio-2.0.so
```

**Comment by BobSynfig** [comment]
Here is a little patch for this issue
https://gist.github.com/BobSynfig/b861ead8ea57df22d601edb22324d6a6

Tested ok with Manjaro current version (in a VM) and it works also fine on Ubuntu 18.04

@MaurycyLiebner: Simply remove these 2 files before create the AppImage
AppDir/usr/optional/libstdc++/libstdc++.so.6
AppDir/usr/lib/libgmodule-2.0.so.0

It seems a lot of AppImages are affected in Manjaro
https://github.com/AppImage/AppImageKit/issues/1162
https://github.com/project-slippi/Ishiiruka/issues/323
https://forum.manjaro.org/t/many-appimages-have-stopped-working-after-todays-update/69445/20

**Comment by MiguelMJ** [comment]
I'll try it out and report soon. Thanks!

**Comment by MiguelMJ** [comment]
It did! Thanks a lot!

**Comment by TheBorzoiOfLight** [comment]
> Here is a little patch for this issue https://gist.github.com/BobSynfig/b861ead8ea57df22d601edb22324d6a6
> 
> Tested ok with Manjaro current version (in a VM) and it works also fine on Ubuntu 18.04
> 
> @MaurycyLiebner: Simply remove these 2 files before create the AppImage AppDir/usr/optional/libstdc++/libstdc++.so.6 AppDir/usr/lib/libgmodule-2.0.so.0
> 
> It seems a lot of AppImages are affected in Manjaro [AppImage/AppImageKit#1162](https://github.com/AppImage/AppImageKit/issues/1162) [project-slippi/Ishiiruka#323](https://github.com/project-slippi/Ishiiruka/issues/323) https://forum.manjaro.org/t/many-appimages-have-stopped-working-after-todays-update/69445/20

Thanks! It worked for me and I'm using Ubuntu 22.04! Idk how that works, but it does!
