### ISSUE TITLE
"Support Enve" button doesn't do anything.

### ISSUE THREAD

**Issue by bobpatraque** [MaurycyLiebner/enve#3]
HI, 

I've discovered the project via Libre Graphic World twitter, and it looks really intuitive !
I would love to support it, but the button doesn't lead anywere...

Also, why not having a patreon page ? (as it is more convenient for a lot of people already using it to support great open source project like yours).

Thank you !

**Comment by MaurycyLiebner** [comment]
As of right now, the amount of money I could collect would be so small it wouldn't make a meaningful impact. When it comes to crowdfunding, the strength is in numbers. Let's wait and see whether enve can get to the stage of development, where it would make sense to crowdfund. I would hate to ask you for donations when I am not sure you can get anything back from it.

**Comment by bobpatraque** [comment]
I understand.

I'm quite sure you could have a real community around your piece of software, as it seems really more slick and intuitive than others FOSS animation projects (which aren't bad at all ! I don't mean to judge or hurt anyone with personal opinions), but it requires time and A LOT of communication (forums, twitter, youtube, etc...). As a one-man project, it could lead to a kind of burn-out pretty quickly...

Anyways, if you'll try to engage more time and work to enve, I would love to be a supporter (as it is the only thing I can do : I do not have any dev skills, and I'm quite sure I'll never have them...)

Thank you for the hard work you've already done ! Enve is a really interesting project and I hope it will continue (if it doesn't, it's okay too. Life's too short to burn-out for free...)

**Comment by morevnaproject** [comment]
> the amount of money I could collect would be so small it wouldn't make a meaningful impact.

That's understandable, but what if to think about it in other way - I am sure some people are happy to donate money as a sign of gratitude for what's you already done. You spent more than 3 years writing code, you open-sourced it - that's already a lot.

So, if not recurring donations, then one-time donations might be good here.

Simple change from "Support Enve" to "Say thanks to developer" and set a link which leads to a page where user offered several choices:
- Make a tweet about Enve
- Donate any amount
- Star repository on GitHub

**Comment by MaurycyLiebner** [comment]
Okey, I hear you.
The enve account on liberapay the button points to is live, just empty for now.
I will look into patreon.
The website is a good idea.

**Comment by MaurycyLiebner** [comment]
Created a Patreon page:
https://www.patreon.com/enve

**Comment by bobpatraque** [comment]
I'm proud to be your first (small) suscriber !

**Comment by MaurycyLiebner** [comment]
Thank you!
