### ISSUE TITLE
Enve .AppImage Won't Run

### ISSUE THREAD

**Issue by Mithufeil** [MaurycyLiebner/enve#309]
The appimage won't run when i execute it. It gave me this:

`enve: /tmp/.mount_enve-cNsB1he/usr/lib/libselinux.so.1: no version information available (required by /lib64/libgio-2.0.so.0)`
`enve: /tmp/.mount_enve-cNsB1he/usr/lib/libselinux.so.1: no version information available (required by /lib64/libmount.so.1)`
`enve: symbol lookup error: /lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full`

I'm on Fedora 36 Xfce

**Comment by BobSynfig** [comment]
Please have a look here https://github.com/MaurycyLiebner/enve/issues/304

**Comment by Mithufeil** [comment]
> Please have a look here #304

When i run the script, this is the output:
`:: enve-c0062e6-x86_64.AppImage present - Skip download
:: AppimageTool present - Skip download
:: Extract the content of the AppImage...
:: Patch
:: Repack/compress AppImage
appimagetool, continuous build (commit 8bbf694), build <local dev build> built on 2020-12-31 11:48:33 UTC
WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
Error: no such file or directory: ./AppDir
:: Cleanup
rm: cannot remove './AppDir': No such file or directory
:: Done`

**Comment by Mithufeil** [comment]
Nevermind, the script worked. I just have to `chmod +x <enve.AppImage>` first (I'm pretty sure i already did that earlier...).
