### ISSUE TITLE
Making Custom Shader Effects

### ISSUE THREAD

**Issue by freewarecamp** [MaurycyLiebner/enve#318]
Can somebody tell me what I have to learn to make custom shader effects? I really want to make some new shader effects for enve but I don't have a single clue how to make them. What I know is i need to make a .gre file & a .frag file with some sort of coding. Please Tell me what coding i need to learn & how to make them if you know. Link some tutorials if you can 🙏

Btw is the whole enve community is dead?😐

**Comment by BobSynfig** [comment]
Hi, there are plenty of resources about this topic:

In enve's docs:
https://maurycyliebner.github.io/docs/shaderEffects.html

On the internet:
https://www.khronos.org/opengl/wiki/Fragment_Shader
https://learnopengl.com/Getting-started/Shaders
https://www.lighthouse3d.com/tutorials/glsl-tutorial/fragment-shader/

You could also been interested in some code of enve:
https://github.com/MaurycyLiebner/enve/tree/master/src/core/shaders
https://github.com/MaurycyLiebner/enve/tree/master/src/core/ShaderEffects
