### ISSUE TITLE
Crash when importing single PNG image

### ISSUE THREAD

**Issue by samytichadou** [MaurycyLiebner/enve#32]
Testing enve continuous build appimage on ubuntu 19.10, i run it from terminal without any extra installations.

I can import PNG image sequence, but the program crash when importing single PNG image (import file operator) 
I get a `segmentation error (core dumped)`
JPG seems to work flawlessly !

**Comment by MaurycyLiebner** [comment]
The issue seems to appear only with the AppImage. Probably something wrong with the Travis CI build.

**Comment by samytichadou** [comment]
Ok, i'm not familiar with building from source, but i can give it a try when i have some time to confirm this !

**Comment by MaurycyLiebner** [comment]
I'm not sure the current build instructions are correct. I didn't test them in a while.

**Comment by MaurycyLiebner** [comment]
Should be fixed with the current build.

**Comment by samytichadou** [comment]
Just tried it, seems to work perfectly ! 
thanks for the quick fix !
