### ISSUE TITLE
AppImage fails to open on Arch Linux

### ISSUE THREAD

**Issue by ghost** [MaurycyLiebner/enve#325]
**Replicate**

1. Download https://github.com/MaurycyLiebner/enve/releases/download/continuous-linux/enve-d919d4d-9_25_22-x86_64.AppImage
1. Run: `chmod +x enve-d919d4d-9_25_22-x86_64.AppImage`
1. Run: `./enve-d919d4d-9_25_22-x86_64.AppImage`

**Expected**

Application runs.

**Actual**

```
enve: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full
```

**System**

``` bash
$ python --version
Python 3.10.9
$ uname -a
Linux hostname 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000 x86_64 GNU/Linux
```

**Possibly Related**

* https://github.com/onivim/oni2/issues/3824
* https://bbs.archlinux.org/viewtopic.php?pid=1994258#p1994258

**Comment by BobSynfig** [comment]
Well known issue, no need to open another one https://github.com/MaurycyLiebner/enve/issues/319
And it is not only about enve
