### ISSUE TITLE
Alt S shortcut for scale reset

### ISSUE THREAD

**Issue by samytichadou** [MaurycyLiebner/enve#34]
the 'alt S' shortcut opens the topbar menu for Scenes, not a bad UX to have all this menu accessible through 'alt First letter of the menu' in a context insensitive way , but it conflicts with the current implementation of the G R S key to manipulate objects on canvas. 
I assumed you are a blender user giving this is the same logic, and this is a great one, 'alt S' should reset the scale of the selected object(s) as 'alt G' and 'alt R' works this way. This would be more consistent i think.
And top bar menu is already accessible through 'alt' then arrows for navigation (or it could be another letter for the Scene)

**Comment by MaurycyLiebner** [comment]
You are correct. I intend to remove them... just forgot. The alt + S simply got overwritten by the menu shortcut.
