### ISSUE TITLE
modal manipulation problem of keyframe in graph editor

### ISSUE THREAD

**Issue by samytichadou** [MaurycyLiebner/enve#37]
when moving or scaling keyframes in graph editor with modal operator (G or S shortcut) you have to click to release the keyframe and exit the operator. 

In the canvas you can press enter to validate, and esc to cancel, which allows user to not apply the transforms.

**Comment by MaurycyLiebner** [comment]
You can also use the right mouse button to cancel. Of course I will add the esc/enter functionality.

**Comment by samytichadou** [comment]
Ok sorry i didn't know that ! i thought it could be something forgotten along the way !
