### ISSUE TITLE
Critical error on stratup

### ISSUE THREAD

**Issue by bobpatraque** [MaurycyLiebner/enve#4]
Hi again.

When I launch appimage on ubuntu 18.04, I get this message :

"4) 102  :  glhelpers.cpp  :  checkCompileErrors()
  ERROR::SHADER_COMPILATION_ERROR of type: FRAGMENT
0(20) : error C7533: global variable gl_FragColor is deprecated after version 120

 3) 161  :  glhelpers.cpp  :  iniProgram()
  Error compiling fragment shader.
 2) 65  :  colorwidgetshaders.cpp  :  iniColorProgram()
  Error initializing color program.
 1) 171  :  colorwidgetshaders.cpp  :  iniColorPrograms()
  Error initializing color programs.
 0) 74  :  effectsloader.cpp  :  initializeGpu()
  Error initializing basic OpenGL programs."

I can't get the colors right and I've got a crash trying to fill a shape with a color.

Os : Ubuntu 18.04
Opengl version : 4.6
Graphic Driver : Nvidia 418.56

**Comment by MaurycyLiebner** [comment]
Sorry about that. Enve was tested only on Intel HD Graphics 3000 and Radeon HD 5550, as they are the only GPUs I happen to own, so there may be some basic compatibility issues/bugs I did not encounter. I will look into this. Would you be willing to test 'fixed' executables if I were to make them available to you?

**Comment by bobpatraque** [comment]
It would be a pleasure !
The executables would be appimage, right ? I suck at compiling...

**Comment by MaurycyLiebner** [comment]
Yes, no worries. I too suck at compiling, so I understand your pain.

**Comment by SavMartin** [comment]
Same problem, with Linux Mint 19.02 , and Nvidia

**Comment by SavMartin** [comment]
then color are not visible en sliders. 
![imagen](https://user-images.githubusercontent.com/30030642/70532008-0bf18c80-1b4e-11ea-85fc-51ebfb832a0a.png)

**Comment by SavMartin** [comment]
And i got this when i click in support 
![imagen](https://user-images.githubusercontent.com/30030642/70532136-5410af00-1b4e-11ea-8ae0-c7ab4c8bd52d.png)

**Comment by MaurycyLiebner** [comment]
Moved on from the deprecated GLSL global output variable "gl_FragColor".
https://www.dropbox.com/s/vsa93dhcdgmcqt7/enve-0.0.0.i4.1.AppImage?dl=0
Does the problem persist? Are there any other problems of a similar nature?

**Comment by ebarranco** [comment]
Hi @MaurycyLiebner  I had the same problem on Manjaro linux and nvidia this new appimage fix the problem now enve starts fine and I can see the color in the selectors. Thanks.

**Comment by MaurycyLiebner** [comment]
Thank you @ebarranco.
@bobpatraque @SavMartin please try it out on your systems, just for the sake of completeness.

**Comment by bobpatraque** [comment]
It seems to be working with me : startup works fine, and I can even fill the circle shape without any crash. Thank you, @MaurycyLiebner.

**Comment by MaurycyLiebner** [comment]
@bobpatraque Does #6 also affect you?

**Comment by bobpatraque** [comment]
It did until now. With 0.0.0.i4,1, I can fill and change colors as much as I want. But it crashes when I move the nodes of a path shape (I don't know if "node" is the right word for it -I'm not a native english speaker-).

**Comment by SavMartin** [comment]
![imagen](https://user-images.githubusercontent.com/30030642/70571600-19326980-1b96-11ea-93ac-e326aaa482e2.png)
Yes now its works

**Comment by MaurycyLiebner** [comment]
@bobpatraque please check the i6.3cpu AppImage in #6.

**Comment by bobpatraque** [comment]
With this version it's flawless. I can move everything I want and change everything I want without crashes.Thank you for your fast reaction !
