### ISSUE TITLE
Please allow arbitrary font size

### ISSUE THREAD

**Issue by prokoudine** [MaurycyLiebner/enve#45]
Right now, font size is limited to 72pt (I'm just assuming it's pt, not px). If I want to get larger text, I need to scale, at which point rasterization becomes obvious even at 400% display resolution depending on actual letters size.

Please allow using larger font sizes by typing the value directly into the combo box.

**Comment by MaurycyLiebner** [comment]
All paths (including text) should be rasterized after transformation is applied, so the only difference should be in the shape of the text, e.g. letter spacing. Font size was intended to be user-editable, it is a focus issue (noFocus vs clickFocus). Thank you for noticing and reporting.
