### ISSUE TITLE
Works great until I go to render. When I try to render I get nothing.

### ISSUE THREAD

**Issue by graphixgeek202** [MaurycyLiebner/enve#48]
On Linux Mint. Am able to animate and set render parameters. When I hit the final render button, Enve crashes. HELP! Does enve require to have ffmpeg already installed on system or does the Appimage already have a version of FFmpeg included?  On Linux Mint installed on a 2008 Mac Pro (Not VM, actual OS).

**Comment by MaurycyLiebner** [comment]
The AppImage ships with FFMPEG. Which version of enve are you using (bottom right corner of the splash screen)? What output settings are you using (format, codec, etc.), or does it happen regardless of the output settings?

**Comment by graphixgeek202** [comment]
Don't know which version it was (not at home or on the computer right now). I was, however, able to export .mkv and .ogg video with no problems. What I was trying to export (and apparently failing miserably at) was image sequences in PNG and JPG (wouldn't do either); failing that I tried to export an mp4 (h.264) and got an empty file...said it was an mp4, but contained no data. Trying to download "enve-43531b1-x86_64.Appimage" now; connection keeps dropping. Assuming that means everyone is just as anxious to get it down considering that it says you released it 5 hours ago. Will have to get it down when I get home. Thank you for your prompt response.

**Comment by MaurycyLiebner** [comment]
I've just checked. You are correct, image sequence output does not work.

**Comment by MaurycyLiebner** [comment]
I think the issues you were experiencing should be resolved now.
Thank you for bringing them to light.
Now all other (potential) users can benefit from it.

If the issues you were experiencing persist, please leave a comment below.
If you find other issues, please open a new dedicated issue.

**Comment by wezm** [comment]
Hi, sorry to dig up an old issue but I'm having exactly the same issues with enve-9ca35e4-x86_64.AppImage. If I render to MP4 I get a 262 byte file that doesn't play. If I render to image sequence no images are produced but if I render to MKV then I do get a working video.

**Comment by MaurycyLiebner** [comment]
I tried rendering to MP4, everything seems to work.

Could you try to render the following file:
[treeSceneSepLeaves.ev.zip](https://github.com/MaurycyLiebner/enve/files/4535183/treeSceneSepLeaves.ev.zip)

If it works it means that it is content/settings specific and it would be great if you would upload the ev file that fails to render, preferably with failing render settings saved.

**Comment by wezm** [comment]
Well I'm not sure what's going on… I was able to successfully render your file to MP4. So then I tried rendering my one again and it worked. Thanks for helping and sorry for the noise.
