### ISSUE TITLE
If I promote group  to Layer I do not think it should be possible to ungroup it...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#51]
If I promote group  to Layer I do not think it should be possible to ungroup it. In this scenario (if you ungroup the layer) the layer disappears and all the paths appear on the timeline sepparately - this creates mess... 

So than I have to select it all make a group again and again promote it to layer and hope to not to make the same mistake again...

**Comment by MaurycyLiebner** [comment]
That's pretty much an issue related to the missing undo/redo capability.
