### ISSUE TITLE
Imported svg files are inaccurate...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#54]
Imported svg files are inaccurate... some path objects from svg file are not correctly imported. The attached zip file contains graphics that I was  importing to enve... test it for yourself. They were made in inkscape and they open in inkscape without any issue.

I think it is a must to have 100% accuracy with svg files, it is a dream workflow to draw in inkscape and animate in Enve, although Enve is very good for drawing as well...

[graphics.zip](https://github.com/MaurycyLiebner/enve/files/4022588/graphics.zip)

**Comment by MaurycyLiebner** [comment]
All ellipses are being imported as ellipses, while in cases where they have matrix-based transformations they should be imported as paths.
