### ISSUE TITLE
Dear developer!  Can compile the installation package for Windows platform?

### ISSUE THREAD

**Issue by vpaintanimation** [MaurycyLiebner/enve#58]
enve looks great!  But unfortunately, I have no programming experience. Only the Linux platform installation package is available in the released option. If you are willing to provide the Windows platform installation package, thank you very much! Apart from this! Do you have a paypal account? I want to donate to this project, although it may not be much, the crowdfunding platform you choose is only suitable for American users

**Comment by hansnolte** [comment]
A Windows version would be really fantastic.
This should give Enve a big population boost.

**Comment by morevnaproject** [comment]
> the crowdfunding platform you choose is only suitable for American users

It is not for American users - I was able to donate from Russia. On this platform you can also use PayPal to donate. ^__^

**Comment by MaurycyLiebner** [comment]
Enve will be Linux only for now. It would require some OS-specific code to make enve work on Windows. I will go back to this in a few months.

There is also [liberapay](https://liberapay.com/enve).

**Comment by vpaintanimation** [comment]
My donation barrier has been resolved🙂
![Screenshot_20200117_191629](https://user-images.githubusercontent.com/25269197/72608745-5d1b4a00-395e-11ea-8382-f34ed7d7c430.jpg)

**Comment by Jose-Moreno** [comment]
I think this should be closed as resolved considering there was a first Windows release on April 4th 2020. Keep up the great work!
