### ISSUE TITLE
Why add the PPAs?

### ISSUE THREAD

**Issue by blackoutworm** [MaurycyLiebner/enve#66]
Hi there.
The GCC 7 version from Canonical's repo is more up to date than the PPA.
The FFMpeg 4 PPA is only a couple version numbers higher then the default repo and it breaks FDK AAC. So is this PPA really needed?
Unless they're actually needed for something, I suggest you remove them from the installation instructions.
They're long and convoluted enough as it is. Just a tip.
And also, you can drop all that qt6, libxkbcommon-x11-dev and symlink stuff by just doing **sudo apt install qt5-qmake qt5-qmake-bin qtcreator**.
No need for qt6. Again, bleeding edge is not necessary just for the sake of it being bleeding edge and making the system unstable. Right?

**Comment by MaurycyLiebner** [comment]
Instructions are for 16.04, as it is the recommended build environment.

>## How to build

>Some of the provided terminal commands are applicable only to Ubuntu 16.04 and 18.04. If you are using a different distribution please treat the commands as a general guide.

**Comment by blackoutworm** [comment]
I get that. I'm on 19.10.
But the thing is. I didn't install Arch. I installed Ubuntu because I prefer things to be somewhat stable.
So if the tools are available in the main repo, please do not use github clones and stuff like that.

**Comment by MaurycyLiebner** [comment]
You don't have to follow build instructions.
They are not available in the main repo on Ubuntu 16.04.

**Comment by blackoutworm** [comment]
But why do you go with 16.04?
The recommended versions are 18.04 and 19.10. 19.04 is end of support very soon.

**Comment by MaurycyLiebner** [comment]
The GitHub clones are for skia, which is a third party dependency.
If you find a better way to build enve on Ubuntu 19.10, please share it.
There is no place for me to put it right now, but I would gladly use it when there is a more robust enve website.

**Comment by blackoutworm** [comment]
Okay I'll work on a 19.10 guide, cuz I'll install it anyway :)
But this is exactly why Snap and Flatpak is so great. No need for the end user to do all this stuff and no need for the devs to write 100 different installation guides.

**Comment by MaurycyLiebner** [comment]
Why aren't you using the continuous build AppImage?
https://github.com/MaurycyLiebner/enve/releases/tag/continuous

You can build it on your own if you want to, but it seems like a lot of hassle given that there is a new (usually) better version pretty much every day.

**Comment by blackoutworm** [comment]
Ah thank you so much. I missed that one.

**Comment by MaurycyLiebner** [comment]
I will put it in the Readme, above the build instructions, so that it is easier to find.

**Comment by blackoutworm** [comment]
👍
