### ISSUE TITLE
Not correctly imported objects from SVG files...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#75]
Not correctly imported objects from SVG files... 

1. 4 nodes path missing one node... 
2. oval - shape changed...

See on videos... also used svg files are included in zip file...

[videos_and_svg_files.zip](https://github.com/MaurycyLiebner/enve/files/4099421/videos_and_svg_files.zip)

**Comment by dadoprom** [comment]
color gradient path object imported from SVG file also behaves weird... but it looks like it is related to this issue as well... try the SVG file included in zip file...

[table.zip](https://github.com/MaurycyLiebner/enve/files/4100115/table.zip)

**Comment by MaurycyLiebner** [comment]
There is a property in SVG called gradientTransform, which causes gradients to have a different direction than specified by the gradient control points. There is no gradient transformation in enve, but I guess I have to implement it now.
