### ISSUE TITLE
Clicking + icon on create new scene Enve crash...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#78]
Clicking + icon on create new scene Enve crash... also I am unable to delete scene with the cross icon... also there should be some warning pop up with confirmation and cancel buttons if you will decide to delete scene...

**Comment by MaurycyLiebner** [comment]
The '+' button is for creating new layouts, not scenes. To create a new scene use Scene -> New Scene from the menu bar.

**Comment by MaurycyLiebner** [comment]
The cross icon resets the layout for the current scene. It is useful when e.g., you open multiple canvases / timelines and want to go back to the default layout. Removing Scenes will be possible from the menu bar Scene -> Delete Scene

**Comment by dadoprom** [comment]
Oh, ok... but what does the "new layout" do? What is its use?

**Comment by MaurycyLiebner** [comment]
You can have a different setup, multiple visible scenes, multiple timelines etc.

**Comment by dadoprom** [comment]
How about custom (user) enabled docks per layout? That would make this perfect...
