### ISSUE TITLE
Visual clue for new blend effect in the timeline

### ISSUE THREAD

**Issue by samytichadou** [MaurycyLiebner/enve#86]
Hey, i just saw the blend effect implementation in your youtube channel (https://www.youtube.com/watch?v=xvDTJrKWmiE), great work !

One thought about it, kind of a feature suggestion : 

this kind of effect could mess with visual representation of the timeline layout order (the top layer could be drawn below the 2nd layer with this kind of override) and the project could quickly become hard to read and understand, for example if you get a project for someone else. 
Maybe it could help to have a visual icon or warning in the timeline panel to let the user know this layer has a blend effect, like a little icon to say "be careful, this one could be displayed in a different order than the timeline one'"

What do you think ?

Cheers !

**Comment by MaurycyLiebner** [comment]
Agreed, this is quite messy, both in the code and in use, but I decided to add it anyway because it seems quite useful. I will try to add some visual indication.

**Comment by MaurycyLiebner** [comment]
![15_1](https://user-images.githubusercontent.com/16670651/74612802-fcbc2b80-5108-11ea-81af-13122f4af975.gif)
