### ISSUE TITLE
Svg import not working correctly, link svg crash Enve

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#87]
Svg import not working correctly, link svg crash Enve...

Svg files are imported partialy or not at all... 
Trying to link svg file - enve crash

**Comment by MaurycyLiebner** [comment]
Please provide an SVG file that is not working correctly and causing crashes.

**Comment by dadoprom** [comment]
here:
[test.zip](https://github.com/MaurycyLiebner/enve/files/4364176/test.zip)

**Comment by MaurycyLiebner** [comment]
Thank you for noticing. The bug was not present in debug builds. Should be fixed with the next build. Text will not be imported from "enve crash.svg", the underlying type is not yet supported.

**Comment by dadoprom** [comment]
Thank you for fixing!
