### ISSUE TITLE
Some objects missing in exported svg file...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#88]
This is what I exported from enve, I exported just 1 frame...
![source](https://user-images.githubusercontent.com/19377506/77248212-f9e8b500-6c37-11ea-9524-53ed331d5159.png)

This is screenshot of the exported svg open in inkscape... some objects are missing...
![export](https://user-images.githubusercontent.com/19377506/77248230-184eb080-6c38-11ea-82cb-b0a8d9c3486d.png)

Here is attached the enve source file - [test_export_to_svg_1.ev.zip](https://github.com/MaurycyLiebner/enve/files/4365100/test_export_to_svg_1.ev.zip)

**Comment by MaurycyLiebner** [comment]
SVG export is currently in active development.
Exporting ellipses to SVG should work when I push today's commits.

**Comment by dadoprom** [comment]
Oh, ok sorry...
