### ISSUE TITLE
Enve for Windows (4_4_20) - Crash

### ISSUE THREAD

**Issue by hansnolte** [MaurycyLiebner/enve#92]
Hi Maurycy,

great that you make a Windows Version for Enve avaible.

Unfortunately Enve crashes at "Initialize custom raster effects..."

My Specs:
Ryzen 5 3600
GTX 1070 - Driver: Standard 442.19 (Studio Version)
32 GB RAM
Windows 10 64Bit Pro - Version 2004 - Build 19041.172

**Comment by MaurycyLiebner** [comment]
Are there any error messages or is it a silent crash?

**Comment by hansnolte** [comment]
It's a silent crash.
Can I activate a logfile via shell?

First:
![first](https://user-images.githubusercontent.com/7922627/78498588-853f6b80-774b-11ea-9e42-5c828b957e91.jpg)

Second:
![second](https://user-images.githubusercontent.com/7922627/78498596-8cff1000-774b-11ea-9640-37d04d5c3e5a.jpg)

Crash.

**Comment by stevphie** [comment]
on my machine everything is working, same os + gpu but different processor + ram size

**Comment by MaurycyLiebner** [comment]
> Can I activate a logfile via shell?
No. Whenever fatal exception is detected, a windows with the error message pops outs.
I will look for potential reasons for that crash in the code. In the meantime you can check out the new Windows release (4/5/20). It handles some new startup errors, not sure whether it covers the issue you are experiencing, though.

**Comment by hansnolte** [comment]
Enve 4/5/20 crashes immediately. 
It doesn't even get to Initialize custom raster effects...

**Comment by MaurycyLiebner** [comment]
Is it a silent crash, or are there any error messages appearing?

**Comment by hansnolte** [comment]
Silent, no error messages.

**Comment by MaurycyLiebner** [comment]
Is the splash screen getting displayed? What is the message on the splash screen when it crashes?

**Comment by hansnolte** [comment]
First:
![first](https://user-images.githubusercontent.com/7922627/78540090-e458bb00-77f3-11ea-9762-9df25c52286e.jpg)

Second:
![second](https://user-images.githubusercontent.com/7922627/78540115-ee7ab980-77f3-11ea-9440-8f6b32f1216f.jpg)

Crash! Without any error messages.

**Comment by MaurycyLiebner** [comment]
Please try 4/6/20. It might produce some meaningful errors.

**Comment by Jose-Moreno** [comment]
@hansnolte Whenever you have a silent crash, you can look at your Windows Event Viewer to produce detailed application crash logs. This is what I did for a recently reported crash bug as well.

Here's a simple guide on how to access it:
https://www.dummies.com/computers/operating-systems/windows-10/how-to-use-event-viewer-in-windows-10/

Make sure you browse to the **Windows Logs > Application** category. Wait for it to load and you'll see the most recent errors there. 

If you see a **Windows Error Reporting** event look on the notes and it will take you to a physical folder location where you'll find a `Report.wer` file which you can open and save as a TXT to share here. Also make sure to copy the **Application Error** Event which should have additional information.

**Comment by stevphie** [comment]
No matter what, I can't trigger this error whatsoever. Any steps to reproduce?

**Comment by hansnolte** [comment]
@MaurycyLiebner
Enve 4/6/20 crashes immediately.
Only one Screen  "Initialize gpu resources" and Crash.
I don't understand it, otherwise everything runs on this machine, even such little divas as Davinci Resolve.

@Jose-Moreno
Thanks for the tip but there are no errors listed.
Can the error log be (unintentionally) deactivated?
![ereignis](https://user-images.githubusercontent.com/7922627/78646072-ce60fe00-78b8-11ea-910f-964594c72b55.jpg)


@stevphie
Install - Start - Crash
(Sorry, but that's really all I do.)

**Comment by MaurycyLiebner** [comment]
I think this is a GPU driver issue. I am trying to find and handle the occurring exception gracefully, so that instead of a silent crash, you get an error message that could point to the solution. I will look through the "Initialize gpu resources" code once again to see whether there are any potential unhandled exceptions.

**Comment by hansnolte** [comment]
Hi Maurycy,
many thanks for your effort.
Which Nvidia driver version are you using?

**Comment by MaurycyLiebner** [comment]
I only have AMD HD 5550, so I don't use Nvidia drivers.

**Comment by MaurycyLiebner** [comment]
Please install 4/7/20 release, open **Command Prompt** and enter:
`"C:\Program Files (x86)\enve_4_7_20\enve.exe" > %HOMEPATH%\Documents\enveOut.txt`

`"C:\Program Files (x86)\enve_4_7_20\enve.exe"` executes enve, make sure the path is correct.
`> %HOMEPATH%\Documents\enveOut.txt` saves output to enveOut.txt in your documents.

Please paste the content of the enveOut.txt file.

You do not have to worry about making a mess with all the enve installs.
When you uninstall enve it leaves no trace behind.

**Comment by hansnolte** [comment]
Install 4/7/20

```
Entered main()
Setup Default QSurfaceFormat
Generated Alpha Mesh
Hardware:
    CPU Threads: 12
         Memory: 32721MB
            GPU: Nvidia

Entered initializeGpu
OffscreenQGL33c initialized
Make OffscreenQGL33c current
iniPlainVShaderVBO
iniPlainVShaderVAO
iniTexturedVShaderVBO
iniTexturedVShaderVAO
iniColorPrograms
Done OffscreenQGL33c current
Entered GpuExecController initialize
GpuTaskExecutor initialized
Entered GpuTaskExecutor::initializeContext
Created GrGLInterface
Created GrContext
iniTexturedVShaderVAO
SwitchableContext set
Done GpuTaskExecutor::initializeContext
```

Enve uninstall leaves traces in 
`c:\Users\MYNAME\.enve`

**Comment by MaurycyLiebner** [comment]
`.enve` folder is the same for all installed enve versions, this is where enve settings are.

It seems that "Initialize gpu resources"  finishes correctly, which means that the exception occurs during subsequent startup stages. Possibly, the message on the splash screen doesn't get updated before the crash. We will get to the bottom of this. I will add more log messages for subsequent startup stages and we will see where the crash occurs.

**Comment by MaurycyLiebner** [comment]
Please execute the same command for 4/8/20, make sure to use the correct (4/8/20) executable.

**Comment by hansnolte** [comment]
Almost..

Shortly after start the Program.
![shortly-after-the-start](https://user-images.githubusercontent.com/7922627/78806726-61865a80-79c3-11ea-8ef2-5df4f8c4f388.jpg)


I push Okay, and it fights... and yes, I'm seeing the Enve surface for the first time.

Did a short aniamtion, two keyframes.
I press Play... Crash

![I wanted to test a short animation](https://user-images.githubusercontent.com/7922627/78806600-2e43cb80-79c3-11ea-81c0-3e4ac9d54cf6.jpg)

```
Entered main()
Setup Default QSurfaceFormat
Generated Alpha Mesh
Hardware:
    CPU Threads: 12
         Memory: 32721MB
            GPU: Nvidia

Entered initializeGpu
OffscreenQGL33c initialized
Make OffscreenQGL33c current
iniPlainVShaderVBO
iniPlainVShaderVAO
iniTexturedVShaderVBO
iniTexturedVShaderVAO
iniColorPrograms
Done OffscreenQGL33c current
Entered GpuExecController initialize
GpuTaskExecutor initialized
Custom path effects initialized
Custom raster effects initialized
Entered GpuTaskExecutor::initializeContext
Created GrGLInterface
Shader effects initialized
Created GrContext
iniTexturedVShaderVAO
SwitchableContext set
Done GpuTaskExecutor::initializeContext
Custom objects initialized
Audio initialized
Render handler initialized
```

It's great that you're working so hard,
Thank you very much Maurycy.

**Comment by MaurycyLiebner** [comment]
We are getting there. I uploaded a new version (4_8_20_a), please check it out.

**Comment by hansnolte** [comment]
YEEEEESSSS Sir it works!
No errors on Starup in Enve 4_8_20_a.

Little Animation (Transform and Fill). 2Keyframes. Works!
Export as MP4. Works!
Export SVG. Crash without Error Message.

I will continue to test and report
Great work Maurycy!

Slowly but surely I have to recharge my Paypal account.


```
Entered main()
Setup Default QSurfaceFormat
Generated Alpha Mesh
Hardware:
    CPU Threads: 12
         Memory: 32721MB
            GPU: Nvidia

Entered initializeGpu
OffscreenQGL33c initialized
Make OffscreenQGL33c current
iniPlainVShaderVBO
iniPlainVShaderVAO
iniTexturedVShaderVBO
iniTexturedVShaderVAO
iniColorPrograms
Done OffscreenQGL33c current
Entered GpuExecController initialize
GpuTaskExecutor initialized
Custom path effects initialized
Custom raster effects initialized
Entered GpuTaskExecutor::initializeContext
Created GrGLInterface
Shader effects initialized
Created GrContext
iniTexturedVShaderVAO
SwitchableContext set
Done GpuTaskExecutor::initializeContext
Custom objects initialized
Using:
    Sample rate: 44100
    Channel count: 2
    Sample size: 16
    Codec: audio/pcm
    Sample Type: 1
    Byte order: 1
Audio initialized
Render handler initialized
```

**Comment by MaurycyLiebner** [comment]
SVG export crashes just after "Export SVG..." is triggered from the menu?
A dialog should be displayed. It works on my machine, but I had people complain to me about it, again, Windows-only issue.

**Comment by hansnolte** [comment]
_"SVG export crashes just after "Export SVG..." is triggered from the menu?"_
Yes.

_"A dialog should be displayed."_
No dialog. Rapidly Crash.

**Comment by MaurycyLiebner** [comment]
SVG export fixed in 4/9/20.

**Comment by hansnolte** [comment]
SVG export works in 4/9/20!
