### ISSUE TITLE
enve2D crashing silently on rendering

### ISSUE THREAD

**Issue by Jose-Moreno** [MaurycyLiebner/enve#93]
### Problem Description
enve2d crashes silently when rendering under windows.

Yesterday I managed to render one video and it crashed. After subsequent tests I can't even get the video, rendering just crashes before completion.

I believe it might have to do with either the type of format i'm exporting to, the settings for that format (how the codecs behave under windows) or the duration of the file as well.

### Reproduction Steps

1. Create a new enve2d file. Make it 15 frames long.
2. Add a simple shape to move (I add a circle)
3. Give it a flat color just to see it, stroke outline doesn't matter
4. Enable the record button for position
5. Animate a simple motion from left to right across the 15 frames
6. Once done, go to Scene > Add to render queue
7. Set the destination first
8. Set the render settings like this:
![image](https://user-images.githubusercontent.com/4912907/78507029-5fae6400-7743-11ea-88e2-ef259d64c9de.png)
9. Press render. Notice the render bar will get up to a certain point and then enve2d will crash.

### System Information
**enve2D Development Build**

commit: https://github.com/MaurycyLiebner/enve/commit/82c76f1cc4920406b688909b57fc9d181a1b0736

+ Win 10 Pro version 1909, OS Build:18363.752
+ AMD FX-6300 6-core 2.81GHZ
+ 16GB RAM
+ Nvidia Geforce GTX 1050 Ti 4GB Windforce OC
+ Driver: DCH 442.19 
+ DirectX Runtime: 12.0

### Attachments / Crash Reports

[Report_04_APR_2020_JoseMoreno.txt](https://github.com/MaurycyLiebner/enve/files/4434522/Report_04_APR_2020_JoseMoreno.txt)
[Extra_Event_Viewer_Log_Reports_04_APR_2020.txt](https://github.com/MaurycyLiebner/enve/files/4434523/Extra_Event_Viewer_Log_Reports_04_APR_2020.txt)

**ev test file** 

Note: this has for me a 100% crash rate when I press render, make sure to change the destination folder, although it'd be interesting to see how it fails when the program can't find the specified folder_
[crash_Test.zip](https://github.com/MaurycyLiebner/enve/files/4434541/crash_Test.zip)

**Comment by MaurycyLiebner** [comment]
I could not reproduce the crash under Linux. I will check it on Windows to see whether it if Windows-specific.

**Comment by MaurycyLiebner** [comment]
I tested it on Linux with Valgrind to see whether invalid memory access or something like that occurs, found nothing. The crash seems to occur during `avformat_free_context` when cleaning up after finished encoding. `avformat_free_context` is part of FFMPEG, so either I am using it incorrectly and it is fatal only on Windows, or this is not an issue with the code, but rather with Windows deployment. To be continued.

**Comment by Jose-Moreno** [comment]
@MaurycyLiebner I see you solved it. I'll test your commit once the continuous integration produces a new build and report back. Thanks! 🙌

**Comment by MaurycyLiebner** [comment]
There are no automatic Windows builds, I have to build Windows releases myself. The current Windows release already has the fix to this issue.
