### ISSUE TITLE
Export Mov-RGBA Crash and no Zoom in Timeline

### ISSUE THREAD

**Issue by hansnolte** [MaurycyLiebner/enve#98]
Quicktime Mov (Codec PNG) with Alpha Channel (RGBA) crashes.
![Crash-Quicktime-Mov-RGBA-export](https://user-images.githubusercontent.com/7922627/78974452-4fff9880-7b12-11ea-8f48-93ed23e6e5f5.jpg)

Testscene:
[Crash-Quicktime-Mov-RGBA.zip](https://github.com/MaurycyLiebner/enve/files/4460525/Crash-Quicktime-Mov-RGBA.zip)

Center the viewport with Numpad-0 and Horizontal Zoom in/out in Timeline and  Graph Editor doesn't work.
How can I see the timeline not only from 0-20 but also, for example to 150 frames?
![timeline](https://user-images.githubusercontent.com/7922627/78974929-58a49e80-7b13-11ea-9047-00c391d0111c.jpg)

Is there somewhere a documentary or Shortcuts for Enve?

Kind regards, Happy Easter - and stay healthy!
Norbert

**Comment by MaurycyLiebner** [comment]
You can use the mouse wheel, while hovering over the bottom range bar, to change the visible timeline range.

**Comment by hansnolte** [comment]
Great!
Thank you very much Maurycy

**Comment by MaurycyLiebner** [comment]
Fixed with 4/10/20. Thank you for reporting. This issue was one of thoses long-lived bugs I simply didn't notice.
