### ISSUE TITLE
Formats files

### ISSUE THREAD

**Issue by mcarluec** [MaurycyLiebner/enve#99]
Hello!
Congratulations for this wonderful little software, so easy to use.
Why are .ev files binary files and not xml files? It would be easier to repair corrupted files for example and consider interoperability.

**Comment by MaurycyLiebner** [comment]
They are binary because they where written as such a long time age.
I considered moving to xml files, just didn't have the time to implement it.

**Comment by MaurycyLiebner** [comment]
Since you brought this up, I will try to focus my efforts on xev, xml based file format for enve. Stay tuned.
